### ISSUE TITLE
Support version key in manifest file

### ISSUE THREAD

**Issue by RolfKirkeng** [jm-73/Indego#121]
Then integration to Homeasistant should be upgraded to use version as reported by HA.
2021-04-11 19:48:41 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'indego'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'indego'

**Comment by Siggy101** [comment]
I have the same in my logs:

2021-05-21 12:28:30 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'indego'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'indego'

**Comment by Siggy101** [comment]
OK, I have updated HA to 2021.6.0 and as expected, this integration no longer works.
I know this is more unpaid work for people but can any dev confirm if this is being worked on?

**Comment by Shamshala** [comment]
@jm-73 Is probably just busy as everybody else. He was recently active at discord server so it's just about not having time to deal with it at this moment, i guess.

Just add the `"version": "0.4",` line manually and you should be good to go on 2021.6

**Comment by Siggy101** [comment]
👍
I totally understand that people are busy and this is not a priority. 
Can you confirm which file I need to add the version line to?  Is it just in the configuration file with the rest of the Indego config or elsewhere?

**Comment by Shamshala** [comment]
@Siggy101 The line belongs to `manifest.json`. :wink:

**Comment by jm-73** [comment]
I have commited the Pr made by Evan. I will have a more in depth look when I have the time. I hope this helps?

**Comment by Siggy101** [comment]
> @Siggy101 The line belongs to `/config/custom_components/indego/manifest.json`. 😉
> 
> **EDIT:** Ups, I had to edit the line above because it was actually a version of another project 😆 . Sorry!

Thanks for the pointers.
I added the version line to the manifest file and all is working perfectly again. 

No rush on the official fix then, this workaround is nice and easy to use for us noobs.
