### ISSUE TITLE
Please add model M+ 700 - currenty "Not in database"

### ISSUE THREAD

**Issue by kondik007** [jm-73/Indego#129]
Hello,

I have bought Indego M+ 700. I have added integration to HA, some sensors are available, but not everything. And model is "Not in database".

Thanks in advance,
Regards,
Konrad

**Comment by jm-73** [comment]
Ok, seems that the mowers model Id is not triggered correctly. I will need you to send logs to me in order to fix this problem. either you publish them here or send me a PM in the Discord channel.

**Comment by jm-73** [comment]
@kondik007 I am still missing logs? Have you sent them?

**Comment by jm-73** [comment]
@kondik007 Logs, please!

**Comment by kondik007** [comment]
Sorry for my delay, but I am currently away from home.
Which logs should I send to you? How can I find it ?

**Comment by jm-73** [comment]
You find the instructions at the bottom of the repository here at Github. I need:
Your HA version
Your indego component version
Your homeassistant.log when you have enabled debug mode
Your custom_configuration/indego/manifest.json

The best way is to send it to me in a DM in Discord!

**Comment by jm-73** [comment]
Should be fixed in 3.8.0
