### ISSUE TITLE
Fix for "Component error" in HA.2021.6.1 not present in HACS

### ISSUE THREAD

**Issue by pinsdorf** [jm-73/Indego#130]
I'm referring to issues #127 and #128 where this component does not load correctly in HA.2016.1 and later. Reason is a missing `version` setting in `manifest.json` as per https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes 

@eavanvalkenburg kindly fixed this in PR #124 and @jm-73 merged it into the code base. Thanks for this!

However, when you install or had installed this component via HACS you do not benefit from this fix. HACS knows only version 3.7 from 4 Aug 2020. Hence, the fix is not present . Please create a version 3.8 so that people get an update notification in HACS. Thanks.

**Comment by jm-73** [comment]
I have checked in some more changes into the develop branch. Will release a new version shortly.

**Comment by pinsdorf** [comment]
Friendly reminder. People on latest HA won't be able to use their Indego without this fix. Thanks.

**Comment by 1192410** [comment]
Yes, please update this. got the same error message and would love to have the component up and running. Thx, Andreas

**Comment by jm-73** [comment]
New version 3.7.1 released!
