### ISSUE TITLE
HA 2021.6.2 breaks indego integration

### ISSUE THREAD

**Issue by snoekieboe** [jm-73/Indego#131]
Hi,

After upgrading to Home Assistant 2021.6.2 the Indego integration is no longer working.
Parsing/validating my configuration before restarting HA results in error:

"Component error: indego - Integration 'indego' not found."

Ik have the following in my configuration.yaml:

```
indego:
  username: !secret indego_username
  password: !secret indego_password
  id:       !secret indego_id
  name:     MowMow
```

What could be going on here?

**Comment by UltraSub** [comment]
See [this](https://github.com/jm-73/Indego/issues/130) issue. Hass doesn't load custom integrations without a version specified in the manifest. It's fixed but not released yet.

**Comment by snoekieboe** [comment]
Is was just reading up on that thnx! and sorry for opening an additional ticket on the topic.

**Comment by jm-73** [comment]
Closing this due to duplicate issue!
