### ISSUE TITLE
Indego S+ 500 not in database

### ISSUE THREAD

**Issue by Siggy101** [jm-73/Indego#135]
Please can we have the new S+ 500 mower added to the database.
At the moment, I am missing some attributes, such as the battery %.  
I would be very happy to help with device specific output, just ask.  

![Screenshot_20210614-203949_Indego Connect](https://user-images.githubusercontent.com/41893936/122024863-1b980400-cdc9-11eb-945f-a710f45f4fad.jpg)
![Screenshot_20210614-163736_Home Assistant](https://user-images.githubusercontent.com/41893936/122024869-1c309a80-cdc9-11eb-9bd4-da49efa339b6.jpg)

**Comment by Siggy101** [comment]
@jm-73 Are you able to add this new model to the db for us please?
I am very happy to run debugs to get model specific info if you need it.  At the moment, I cannot get battery % readout.

**Comment by jm-73** [comment]
Coming in the next release (waiting for code review).

**Comment by Siggy101** [comment]
That's awesome news.  Thank you so much for your work.  It is really appreciated.
My offer still stands to do any testing/logs you need with this new model.

**Comment by jm-73** [comment]
Should be fixed in 3.8.0

**Comment by Siggy101** [comment]
Thank you so much!  I confirm my S+ 500 is working perfectly now with no manual edits of manifest.json
