### ISSUE TITLE
Lawn mowed saturates at 98%

### ISSUE THREAD

**Issue by andre-richter** [jm-73/Indego#139]
I'm curious if anyone else sees this:

The `lawn_mowed` sensor for my M 700 always saturates at 98%, never goes to 100%, even if the lawn mowing clearly has completed.

If other see that too, it might be worth adding a small quirk to the code that bumps the sensor reported value from 98% -> 100%.

Thanks,
Andre

**Comment by UltraSub** [comment]
It's what the api reports. And it fluctuates. Currently for me the Bosch app reports a completed mow, but percentage wise I'm seeing 89% completed. And I've seen other values too (I've also seen the 98 you're seeing, but also like 93%, so it really varies). I guess it actually skips some parts of the lawn sometimes but doesn't bother to go back for a small spot and reports mow complete.

**Comment by andre-richter** [comment]
Okay, if it is fluctuating this much, it might not be trivial to hardcode a quirk for saturation that works for everyone.

One approach could be to give users an optional variable in `configuration.yaml`, and the `lawn_mowed` sensor then does:

```python
if lawn_mode_percent >= user_lawn_mode_complete_threshold
    return 100

return lawn_mode_percent
```

**Comment by jm-73** [comment]
You can modify the custom_component in what way you want. that is the beauty of open-source. But I am not going to change the custom_component in order to get 100% if the API doesnt report that. The component is reporting the information it can read and understand from the API. So no change for now.

**Comment by jm-73** [comment]
You could make a template-sensor with the function you described above. Maybe that is the easiest solution.
