### ISSUE TITLE
[Request] Provide indego informations as attributes in addition to entities

### ISSUE THREAD

**Issue by xguitoux** [jm-73/Indego#141]
Hey there,

I'm making a custom card for our indego mowers 
First draft example : https://cdn.discordapp.com/attachments/719165482346741777/869572421525598258/unknown.png

But in order to be user friendly it's better to provide only 1 entity (main indego entity, maybe "connected" value) with custom attributes (battery, mowing mode etc.) I had to make a custom entity with a template 

` platform: template
  sensors:
    tondeusebosch:
      friendly_name: Tondeuse Bosch
      value_template: states.binary_sensor.indego_xxxxx_online_2.state
      attribute_templates:
        battery: >
          {{states.sensor.indego_xxxx_battery_percentage_2.state}}
        details: >
          {{states.sensor.indego_xxx_mower_state_detail_2.state}}
        status: >
          {{states.sensor.indego_xxx_mower_state_detail_2.state}}
        connection: >
          {{states.binary_sensor.indego_xxxx_online_2.state}}
        lawn_mowed: >
          {{states.sensor.indego_xxx_lawm_mowed_2.state}}
        mode: >
          {{states.sensor.indego_xxxx_mowing_mode_2.state}}
        last_completed: >
          {{states.sensor.indego_xxxx_last_completed_2.state}}
        mowtime_total: >
          {{states.sensor.indego_xxxxx_runtime_total_2.state}}`

Is it possible for you to add custom attributes to the main entity ?

Thank you

**Comment by jm-73** [comment]
@eavanvalkenburg  I need your comment on this!

**Comment by eavanvalkenburg** [comment]
@xguitoux  and @jm-73  I see the asks but since we also have the seperate sensors, I'm not sure this is the way to go, for two reasons, 1) there is work being done to create a dedicated Mower entity HA wide, so depending on what that looks like we should make sure this visual aligns with that effort 2) in general it makes more sense to get the visual to pull in states from multiple entities because then different mowers (existing ones) can also use this visual, but I have never developed a visual so not sure how easy that is...

**Comment by xguitoux** [comment]
@eavanvalkenburg Hello and thank you for the answer, my small work was based on a xiaomi vacuum, but in general when you add a custom card for a group of entities you only add the main sensor and all other informations are based on attributes. 

But again it's my first attempt to make a custom card, there may be a better way to implement it...

**Comment by eavanvalkenburg** [comment]
@xguitoux no problem, let me know if you figure out a way to use multiple sensors, that would be my preference and is most likely to align with HA guidance!

**Comment by eavanvalkenburg** [comment]
I use this one that has multiple sensors as input: https://github.com/gurbyz/power-wheel-card

**Comment by xguitoux** [comment]
@eavanvalkenburg If you stick with the naming convention of your indego sensors I can maybe manage to generate all needed sensors based on the state on, but I will have to use regular expressions and I hate that ^^

Do you have a link to the HA guidance for sensors/attributes ?

**Comment by urbatecte** [comment]
Hi,
By the way, if you find a way to display "Last completed..." in a "normal" display, it will be great I've try to change the format but unsuccessfully :-(

![image](https://user-images.githubusercontent.com/37276346/127836220-69a7a35f-4515-4827-befc-ff4263b1b647.png)

May be more like that:
![image](https://user-images.githubusercontent.com/37276346/127837025-e14e7ce3-0402-46d0-b664-f7899ced8e64.png)

Thanks a lot !

**Comment by xguitoux** [comment]
![image](https://user-images.githubusercontent.com/5737421/127837366-ad33d798-a214-4575-a61f-38e328af1486.png)

Salut @urbatecte, I changed a little the template to display how many days ago last mow was made with this in the template
```
 last_completed: >
          {{ relative_time(states.sensor.indego_XXXXX_last_completed.state|as_datetime) }}
```
For a friendly display of the date I'm not sure how to do it for now

**Comment by urbatecte** [comment]
Fantastic @xguitoux, but here is my noob question:
Should I add this template in the card or in the configuration.yaml or somewhere else ?

**Comment by Shamshala** [comment]
Try edit [this](https://github.com/jm-73/Indego/blob/master/custom_components/indego/__init__.py#L174) and [this](https://github.com/jm-73/Indego/blob/master/custom_components/indego/__init__.py#L182) from `"ISO8601"` to `None` and you shouldn't have to do that modification.

**Comment by urbatecte** [comment]
Thanks @xguitoux and @Shamshala .

I'm quite happy with templating.
![image](https://user-images.githubusercontent.com/37276346/127847543-fe70481d-4f29-46a1-8824-5c51ebdada83.png)

I prefer to keep @jm-73 code as is in order to be update-proof :-)

I will dig a bit more within the timestamp_custom.

**Comment by xguitoux** [comment]
I've managed to work without attributes and custom template, you can find v1 here https://github.com/xguitoux/lovelace-bosch-indego-card

**Comment by eavanvalkenburg** [comment]
Super cool @xguitoux !

**Comment by urbatecte** [comment]
Hi @xguitoux ,
I've try your card but, I didn't succeed..
![image](https://user-images.githubusercontent.com/37276346/128226896-7064f34e-43c2-4894-8438-b7aa39fc1995.png)
Even if when I click on the icon it seems that the entity is reached ?
![image](https://user-images.githubusercontent.com/37276346/128227078-a9b89b94-a07d-4245-8f63-14a86e8f8534.png)

By the way, you may have to open the issue in your repository (that why, I post here)
Thanks

**Comment by xguitoux** [comment]
@urbatecte Didnt saw that issues had to be opened, it's now done, can you open one in my repo and post your config, maybe a screenshot of F12 console when you load the card ? Thank you
