### ISSUE TITLE
Suggest Vaccum Entity

### ISSUE THREAD

**Issue by pfriedrich84** [jm-73/Indego#142]
Hi,
maybe its usefull or even gets implemented in the component. I've added a control entity for Dolly:

`
vacuum:
  - platform: template
    vacuums:
      dolly:
        friendly_name: "Dolly the e-Sheep"
        unique_id: "dolly_700xxxxxx"
        battery_level_template: "{{ states('sensor.indego_700xxxxxx_battery_percentage')|int }}"
        value_template: >-
          {% set state = states("sensor.indego_700xxxxxx_mower_state") %}
          {% set num = state_attr("sensor.indego_700xxxxxx_mower_state_detail", "state_number")|int %}
          {% if num >= 769 and num <= 776 %}
          returning
          {% elif state == "Mowing" %}
          cleaning
          {% elif state == "Docked" %}
          docked
          {% else  %}
          error
          {% endif %}
        start:
          service: indego.command
          data:
            command: mow
        pause:
          service: indego.command
          data:
            command: pause
        return_to_base:
          service: indego.command
          data:
            command: returnToDock
`

**Comment by Vitani** [comment]
Slightly tweaked your YAML, and thought I'd share it (PS. you need to use three backticks to format multi-line code on GitHub)
```
vacuum:
  - platform: template
    vacuums:
      lawn_mower:
        friendly_name: "Lawn Mower"
        unique_id: indego_XXXXXXXX
        start:
          service: indego.command
          data:
            command: mow
        pause:
          service: indego.command
          data:
            command: pause
        return_to_base:
          service: indego.command
          data:
            command: returnToDock
        value_template: >-
          {% set state = states("sensor.indego_XXXXXXXX_mower_state") %}
          {% set num = state_attr("sensor.indego_XXXXXXXX_mower_state_detail", "state_number") | int %}
          {% if num >= 769 and num <= 776 -%}
            returning
          {%- elif state == "Mowing" -%}
            cleaning
          {%- elif state == "Docked" -%}
            docked
          {%- else -%}
            error
          {%- endif %}
        battery_level_template: "{{ states('sensor.indego_XXXXXXXX_battery_percentage') | int }}"
        availability_template: "{{ states('binary_sensor.indego_XXXXXXXX_online') }}"
        attribute_templates:
          alert: "{{ states('sensor.indego_XXXXXXXX_alert') }}"
          lawn_mowed: "{{ states('sensor.indego_XXXXXXXX_lawm_mowed') }}"
          last_completed: "{{ states('sensor.indego_XXXXXXXX_last_completed') }}"
```

**Comment by pfriedrich84** [comment]
thanks for the input . I wasn't aware of the attribute_templates.

**Comment by jm-73** [comment]
Still waiting for some PRs... ;-)

**Comment by jm-73** [comment]
No PRs recieved. If no one is interested in doing the job, this will remain unfixed!

**Comment by pfriedrich84** [comment]
Already checked for the vacuum.py from other integrations, but not able to get it running.
i'm an ABAP/PHP guy, phython is difficult for me, sorry ;)
