### ISSUE TITLE
Lawn mowed % delayed and incorrect

### ISSUE THREAD

**Issue by huub66** [jm-73/Indego#143]
The lawn mowed indicator is rather infrequent in updates, is this because of API limitations? What kind of update frequency is offered by the API. Battery is updated every few minutes for instance but 'lawn mowed' remains on 0% even when the Bosch Smart Gardening app is displaying about 80% complete when charging for a 2nd round of mowing.

Looking forward to some insight :)

**Comment by jm-73** [comment]
It is taken from the API. So it is not possible to get more frequent updates. Sorry.

Closing issue as it is a limitation in the API.
