### ISSUE TITLE
Next mow time in past

### ISSUE THREAD

**Issue by Rantaki** [jm-73/Indego#144]
I noticed that by switching back and forth the SmartMowing and manual mowing (via the Bosch app) Home Assistant now shows the next mow time in past (i.e. one day ago). I'm not exactly sure how I did this (using the Bosch app anyway), but it would be good if the next mow time entity value would be "no plans" e.g. in case the time is in the past. At the same time the Bosch app shows that there is no plans to mow.

**Comment by jm-73** [comment]
Is this still an error? I dont use the shceduler in the app anymore. I schedule the mower in HA instead.

**Comment by Rantaki** [comment]
Don't know. Need to check it again on summer.
