### ISSUE TITLE
Where's the API path stored?

### ISSUE THREAD

**Issue by MagaliDB** [jm-73/Indego#145]
So I learned that the Honda Miimo HRM 40 Live mower is basically the same as the Bosch Indego S+ 400 mower, and most of the functionality is also identical. So I'm trying to use your custom component, but with the connection to the Honda API. But I can't seem to find where you've put the path? I know for the Indego it's api.indego.iot.bosch-si.com and I want to replace it with api.miimo.honda.co.uk. :)

**Comment by jm-73** [comment]
I think you got it working accourding to what you rote in the Discord channel.

Closing the issue.
