### ISSUE TITLE
Entity sensor.indego_last_completed implements device_state_attributes

### ISSUE THREAD

**Issue by mirkin1993** [jm-73/Indego#153]
Hi,

Home assistant gives the following errors:
Entity sensor.indego_last_completed (<class 'custom_components.indego.sensor.IndegoSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.indego_next_mow (<class 'custom_components.indego.sensor.IndegoSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.indego_mowing_mode (<class 'custom_components.indego.sensor.IndegoSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.indego_runtime_total (<class 'custom_components.indego.sensor.IndegoSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by jm-73** [comment]
I think this will be solved in PR #159

**Comment by jm-73** [comment]
Solved in 4.0
