### ISSUE TITLE
Error 400 and 429

### ISSUE THREAD

**Issue by abeltman** [jm-73/Indego#154]
I bought a Indego S+ 350 in January and have just installed it this past weekend. When I install the HACS integration and make the necessary changes in the configuration.yaml the status of the entities remain unknown and I see the following errors in the log.

----
Logger: pyIndego.indego_async_client
Source: /usr/local/lib/python3.9/site-packages/pyIndego/indego_async_client.py:521
First occurred: 12:54:56 (189 occurrences)
Last logged: 12:56:08

400: Bad Request: won't retry. Message:
----
Logger: pyIndego.indego_async_client
Source: /usr/local/lib/python3.9/site-packages/pyIndego/indego_async_client.py:577
First occurred: 12:55:28 (29 occurrences)
Last logged: 12:56:57

429, message='', url=URL('https://api.indego.iot.bosch-si.com/api/v1/alms/5704093/state?longpoll=true&timeout=300&last=0'): Failed GET to Indego, won't retry
----

I noticed similar issues on #146, #147 and #148 but a fix has been provided for those.

Any thoughts how to get my Indego working with HA?

**Comment by abeltman** [comment]
Many thanks for the suggestion! I have tried to remove the special character I did have in my initial password but that hasn't resolved my problem. It's now just lowercase, uppercase and numbers but still no joy.

**Comment by abeltman** [comment]
Just to add... the Bosch Smart Gardening app is working fine until I activate the Indego integration in HA. It then stops working and also gives the 429 error.

**Comment by jm-73** [comment]
The integration only supports email login. Maybe you have connected your Bosh Indego account to Facebook?

the errors you describe sounds a lot like login problems to me.

**Comment by abeltman** [comment]
I am using email login. And the integration does seem to affect my account, else it wouldn't have an impact on the Bosch app when I activate the integration. So you may be right saying it's login problems, but can't figure out how/what. Just to check... the id is always 9 digits, right? Including the first 0?

**Comment by UltraSub** [comment]
429 is the Bosch api telling you: "too many requests". The Bosch app is using the same api, so it'll stop working for some time too if it's using the same id. I would advise disabling this integration, wait some time and try to login in the official app. The moment that works, retry setting up the hass integration with the exact same credentials. If this hass integration is retrying with the wrong credentials you will run into 429 again. Make sure the official app is working fine first.

**Comment by abeltman** [comment]
I have checked the credentials in HA over and over again. I have tried putting the credentials in the configuration.yaml, avoiding secrets.yaml but no difference.

Bosch app - working fine
https://indego.grauonline.de/ - working fine
Home Assistant integration - not working

**Comment by jm-73** [comment]
Just to make sure that this isnt an easy fix:
Can you send me the yaml login settings you are using? Maybe you found a bug?

And I also need a homeassistant log file (with debugging activated) to be able to do some troubleshooting.

**Comment by jm-73** [comment]
You can send me a DM in Discord!

**Comment by nblount** [comment]
I have tried to set this up and eventually opened a case with Bosch and they said the API is no longer supported so my account which has only been recently created will not work, they are not activating new accounts on the API or at least that is how I understand it.

**Comment by jm-73** [comment]
Bosch has nothing to do with your problems. You are doing something wrong. I have offered you to send me logs (which I havent recieved).

Please try:
Reinstall the addon via HACS
Reinstall the addon manually
Reinstall HASSIO on another device and try the addon there
Send me the logs I requested

I will remove this issue as it is only you who experience this kind of problem. This ADDON is an unsupported use of the Bosch API so please dont bother Bosch with further questions. And please tick of the whole list above in order to troubleshoot your problem.

**Comment by nblount** [comment]
Would agree if it wasn’t for the fact that I get error 401 using https://indego.grauonline.de/ as well and no matter what I change my password to makes no difference basically my account does not work with the API regardless of the software used.

**Comment by jm-73** [comment]
I remove this issue because I dont get any feedback in what kind of troubleshooting the user has performed. Nor has any logs been presented to me.
