### ISSUE TITLE
Typo in 'Lawn Mowed' sensor name

### ISSUE THREAD

**Issue by Vitani** [jm-73/Indego#155]
The Lawn Mowed sensor is called `lawm_mowed`, instead of `lawn_mowed`. See https://github.com/jm-73/Indego/blob/master/custom_components/indego/const.py#L21

Happy to raise a PR myself, but it will be (for some) a breaking change.

**Comment by jm-73** [comment]
Do a PR so I cna fix this!

**Comment by jm-73** [comment]
Fixed in 4.0
