### ISSUE TITLE
question - how generate a command for mow an dock or pause

### ISSUE THREAD

**Issue by Donni1966** [jm-73/Indego#156]
Sorry about this maybe stupid question. But i look for an example how create a command i can use later in the dashboard like a switch. 

i do not see the service in the list when i try to put it on a card

i am not very good in using home assistant.

Somebody have a short "how to" for me? 
byby, Michael

**Comment by JensMKofoed** [comment]
Hi

If you go to Configuration - Automations & Scenes - Scripts
you can create a script the following:
Action type: Call service
Service: Bosch Indego Mower: command
Service data: command: mow

the commands are either mow, pause or returnToDock

you can call these commands from automations and buttons on the dashboard. You can also do the Call service directly from a button or a automation so you don't have to create a script.
unfortunately you can not call a script nor automation from a scene. So I've not found a way to send the commands via a scene yet

Kind regards
Jens

**Comment by Donni1966** [comment]
Thanx a lot … now I unterstand this also :-)

**Comment by jm-73** [comment]
Solved!
