### ISSUE TITLE
Uncaught error: __init__() got an unexpected keyword argument 'data' on index: 1

### ISSUE THREAD

**Issue by galex80** [jm-73/Indego#160]
Hi Guys,
yesterday, my Indego S 350 received a new firmware update. Since then, following error appears in Log of Home Assistant. Unfortunately, debug log doesn't give any further details than the log below:

```
2022-05-19 15:49:34 DEBUG (MainThread) [custom_components.indego] Refreshing state.
2022-05-19 15:49:35 WARNING (MainThread) [custom_components.indego] Uncaught error: __init__() got an unexpected keyword argument 'data' on index: 1
2022-05-19 15:49:35 DEBUG (MainThread) [custom_components.indego] Refreshing initial operating data.
```

Indego-Software
Current Firmware-Version: 30036.01251 (error in log)
Previous Firmware-Version: 7.12.27357 (no error in log)

Home Assistant Software
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.0

Any help is much appreciate.

**Comment by jm-73** [comment]
Isn't the integration starting at all?

**Comment by jm-73** [comment]
Please send debug from clean startup. Log may be sent to me in Discord.

**Comment by galex80** [comment]
Hi Jens, 
i will close this issue, since the error doesn't appear anymore since latest update of integration. 
If the error will popping up again, i will open a new issue.

Best regards,
Alex
