### ISSUE TITLE
'Indego alert' always returns "Problem"

### ISSUE THREAD

**Issue by 35aportal** [jm-73/Indego#164]
All,
How can I make use of the 'Indego altert' sensor? It used to return things like 'Reminder blade life', but now shows 'Not in database.'

Many thanks in advance.

**Comment by jm-73** [comment]
If the "Not in databes" is showing, I would be glad to have the error code and the actual error. The"Not in databes" means that the integration dosent have the error code for the error you have experienced. Try the debug mode if it isnt abvious in the integration itself and try to find it in the logs.

**Comment by jm-73** [comment]
I have published a bug fix that solves the problem with the alert sensor always be flagged as "Problem".

**Comment by 35aportal** [comment]
I've updated and can confirm that the fix worked for me. Thanks for taking care of this and for the generally awesome work with the integration.

**Comment by 35aportal** [comment]
Confirmed fixed in 4.0.1

**Comment by Pr0mises** [comment]
I've updated it aswell, now the sensor shows "Problem" and the history "on". I do have 10 Alerts in Attributes even though I marked them as read in the app.
![indego](https://user-images.githubusercontent.com/21245147/182511521-5c364a69-f902-4096-8e5d-fea732c9ad25.png)



I also found 2 more alerts (translated with deepl as I'm unsure where to change the language in the Bosch app)
error_code: 1138
English(UK):
```
"headline": "Mower needs help."
"message": "Mower is at a standstill Your Indego is at a standstill. Please place the mower on a level lawn and follow the instructions on the mower's display. If the problem persists, please switch the Indego and charging station off and on again."
```
German:
```
"headline": "Mäher benötigt Hilfe."
"message": "Mäher steht still Ihr Indego steht still. Bitte stellen Sie den Mäher auf eine ebene Rasenfläche und befolgen die Anweisungen im Display des Mähers. Wenn das Problem weiterhin besteht, schalten Sie bitte Indego und Ladestation aus und wieder ein."
```

"error_code": "firmware.updateComplete"
Englisch(UK):
```
"headline": "Maintenance Note."
"message": "Software update completed. Congratulations! The downloaded software has been successfully installed."
```
German:
```
"headline": "Wartungshinweis."
"message": "Aktualisierung der Software abgeschlossen. Gratulation! Die heruntergeladene Software ist erfolgreich installiert worden."
```

**Comment by jm-73** [comment]
You have to delete the alerts in order for the sensor to show OK.

**Comment by jm-73** [comment]
I will release an update for your error messages. If you want to try them before you delete the alerts.

**Comment by Pr0mises** [comment]
> I will release an update for your error messages. If you want to try them before you delete the alerts.
> 

Alerts are working now thanks, is it possible to add the ability to delete alerts from hass aswell?
