### ISSUE TITLE
Send mower to a specific location 

### ISSUE THREAD

**Issue by kaystrobach** [jm-73/Indego#165]
It would be awesome to be able to send the mower to a specific location and start spot-mow at that point.

**Comment by Shamshala** [comment]
Does something like that even work via app?

**Comment by kaystrobach** [comment]
Atleast i did not found it. But sometimes the APIs offer more than the Apps 😅

Spotmow is indicated in the App, but i can
not trigger it there.

**Comment by jm-73** [comment]
The API is undocumented. Most of the work has been done by people reverse-engineering the Android app. So if someone get hold of infoemarion about spot-mowe I will be happy to include this in the app.
