### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by Merexor** [jm-73/Indego#167]
Hallo Zusammen,

Ich habe alles installiert und in der Konfiguration so eingetragen wie in der Anleitung.
Aber die Anmeldung schlägt immer wieder fehl.
Ich habe einen Bosch Indego S+ 500.
Hoffe auf Hilfe.

LOG:
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht  
Logger: custom_components.indego 
Quelle: custom_components/indego/__init__.py:233 
Integration: indego (Dokumentation) 
Erstes Ereignis: 19:08:48 (1 Vorkommnisse) 
Letzter Besuch vor: 19:08:48  
Login nicht erfolgreich: Anmeldung kann nicht möglich sein, bitte überprüfen Sie Ihre Anmeldedaten

**Comment by jm-73** [comment]
Please write in english!
I have also problems with the integration. It seems that there are a login problem?
The App is working for me. Anyone else who can confirm/deny if this is a widespread problem or just for me and Merexor?

**Comment by Merexor** [comment]
Sorry, I saw it too late.
It would actually be easy to configure but unfortunately it keeps failing.
So I don't know exactly why this happened.

**Comment by mrtobs1** [comment]
Same here sometimes… i have 2 indegos and the one i am not logged in in the iphone-app sometimes gets unavailable in HA. When i log in with the other account on the app and restart HA, some minutes/hours later they work both again. Now they work since some days without problems. Hope that helps maybe to find the problem?

**Comment by Shamshala** [comment]
@mrtobs1 Simple, Bosch's server doesn't support multiple simultaneous connections to one account at a time so when you connect via app, your HA is kicked out.

**Comment by Merexor** [comment]
My Problem is that the connection failed since day one. So i didn't have the problem that i lost the connection, the connection didn't even work.

**Comment by Merexor** [comment]
@jm-73 do you have a idea ..?

**Comment by jm-73** [comment]
My login problems was solved when I updated HA.

**Comment by jm-73** [comment]
@Merexor I need debug logs from a fresh reboot in HA. All "unsolvable" login problems with the integration has been solved when analyzing the debug logs or when I have analyzed the user/password used to login. For example when you have a serial number starting with a "0" you have to use "" wround the password in your secrets.yaml.

**Comment by Merexor** [comment]
@jm-73 all my settings:
!secrets.yaml
indego_username: "ma*********er7@gmail.com"
indego_password: "C*****-******-******"
indego_id: "2*******0"

logs:
----------------------------------------------------------------------------
Logger: custom_components.indego
Source: custom_components/indego/__init__.py:233 
Integration: indego ([documentation](https://github.com/jm-73/Indego)) 
First occurred: 22:15:49 (1 occurrences) 
Last logged: 22:15:49

Login unsuccesfull: Unable to login, please check your credentials
----------------------------------------------------------------------------

**Comment by NJ-89** [comment]
Hi, 
I seem to have the same problem with the integration of my S+ 500.

My most recent logs after upgrading to the latest version on Home Assistant:

> 2022-11-05 15:50:33.110 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration indego which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2022-11-05 15:51:32.424 DEBUG (MainThread) [pyIndego.indego_async_client] Sending GET to https://api.indego.iot.bosch-si.com/api/v1/authenticate/check
> 2022-11-05 15:51:41.066 DEBUG (MainThread) [pyIndego.indego_async_client] [Errno 104] Connection reset by peer: Failed to update Indego status, longpoll timeout
> 2022-11-05 15:51:41.077 WARNING (MainThread) [custom_components.indego] Login unsuccesfull: Unable to login, please check your credentials
> 2022-11-05 15:51:41.122 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration indego: Integration failed to initialize.

It looks like a time-out with the server might be the problem. If so can I and @Merexor do anything to solve the issue?

**Comment by jm-73** [comment]
I have also had periods with failed login during the last weeks. It seems to me that Bosch have had some problems. Today my login was indeed successful after rebooting my HA. Please try again!

**Comment by NJ-89** [comment]
I tried it again, different error message this time:

> 2022-11-08 19:20:21.261 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration indego which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2022-11-08 19:20:46.531 DEBUG (MainThread) [pyIndego.indego_async_client] Sending GET to https://api.indego.iot.bosch-si.com/api/v1/authenticate/check
> 2022-11-08 19:20:49.295 DEBUG (MainThread) [pyIndego.indego_async_client] status: 401
> 2022-11-08 19:20:49.300 INFO (MainThread) [pyIndego.indego_async_client] 401: Unauthorized, credentials are wrong, won't retry
> 2022-11-08 19:20:49.300 WARNING (MainThread) [custom_components.indego] Login unsuccesfull: Unable to login, please check your credentials
> 2022-11-08 19:20:49.358 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration indego: Integration failed to initialize.

So it doesn't seem to accept my credentials. So I did a bit of digging in the code to see how the authentication works and used postman to replicate the issue.
https://api.indego.iot.bosch-si.com/api/v1/authenticate always returns 401 for my credentials even after adjusting them.

Could it be there is a different URL for different countries/continents? I haven't been able to find any documentation about the API. So, hopefully you have an idea.

**Comment by jm-73** [comment]
If you want you can send me your login credentials and I will try them out for you. I order to test if your theory is correct?
Easiest way is to send both debug logs and credentials in a private message on Discord.

**Comment by jm-73** [comment]
Closing the issue as I dont get information enough to solve this.

**Comment by Merexor** [comment]
@jm-73 
I've also tried it again several times.. but it doesn't work.  no matter how I specify user/password/serial number

what do you need to test it?

**Comment by jm-73** [comment]
Send me a private message on Discord with your login credentials. Then I can try to login and get a celan log file. I have solved every issue this far with people having trouble logging in. Your choice...

**Comment by Merexor** [comment]
@jm-73 already wrote to you. hope the message has reached you.

**Comment by jm-73** [comment]
@Merexor got the message. Hear from you in a week then.

**Comment by Merexor** [comment]
do you need a moving robot or is there just an API access to the Bosch server ..?

**Comment by Merexor** [comment]
@jm-73 Do you have time this week?

**Comment by Merexor** [comment]
@jm-73 when do you have time ?

**Comment by Merexor** [comment]
@Shamshala @NJ-89 
Problem solved.. i had "-" in My password .. that was the Problem .. maybe it's help you 👍🏻
