### ISSUE TITLE
Feature request set as vacuum

### ISSUE THREAD

**Issue by MartinKuhl** [jm-73/Indego#168]
Hi,
as an idea tu use the new feature if the tile card: https://www.home-assistant.io/dashboards/tile/#vacuum-commands 
would it make sense to set the mower as a vacuum cleaner inside of home assistant?
Docs: https://www.home-assistant.io/integrations/vacuum 

Technically it should be nearly the same.

**Comment by Merexor** [comment]
@MartinKuhl 
I using this: https://github.com/xguitoux/lovelace-bosch-indego-card

@jm-73 
Maybe this could integrated with your intergration + expented with Issue/Idea (Garden Map #133)

**Comment by jm-73** [comment]
Doesnt seem like anybody is up to the challenge. Maybe it is time to close this?

**Comment by sander1988** [comment]
This is useful in my opinion so I have implemented it: https://github.com/sander1988/Indego/tree/issue168_expose_mower_as_vacuum

![image](https://user-images.githubusercontent.com/6334319/229173327-3da9fe27-2780-4f9e-85cf-218fe1019eb9.png)


I have not yet created a merge request as it is blocked by #173

**Comment by jm-73** [comment]
Commited into dev branch. Please test this out and give me feedback.

**Comment by jm-73** [comment]
You can test this by downloading the dev branch and replace the code on your HA with this code. I will try to release a beta of this plugin shortly (maybe this weekend).
