### ISSUE TITLE
Expose all used string for translation

### ISSUE THREAD

**Issue by RolandE1204** [jm-73/Indego#178]
It would be nice if ALL used strings (State, Problems, ...) in the integration could be translated (I would be proud to do the translation to German)

**Comment by LarsLautrup** [comment]
I agree - and I volunteer to do the translations into Danish!

**Comment by wimb0** [comment]
Good idea. I can help with Dutch

**Comment by FBruynbroeck** [comment]
👍 And me with French 😉

**Comment by zmechu** [comment]
Can help also in Polish. How to help? :-)

**Comment by wimb0** [comment]
I've started working on the Dutch translation. First part is done, see https://github.com/jm-73/Indego/pull/196
To translate all strings (sensors/services etc.) more work needs to be done on the integration itself.
For what I understand, every entry that needs to be translated needs a key and translation_key.
See https://developers.home-assistant.io/docs/internationalization/custom_integration/ and https://developers.home-assistant.io/docs/internationalization/core

**Comment by zmechu** [comment]
Cant do it on github, so putting just here (pl.json)
```
{
    "config": {
        "abort": {
            "already_configured": "Ta kosiarka Bosch Indego została już skonfigurowana wcześniej!",
            "connection_error": "Błąd połączenia z Bosch Indego API!",
            "no_mowers_found": "Nie znaleziono żadnej kosiarki na tym koncie Bosch Indego!"
        },
        "step": {
            "mower": {
                "data": {
                    "mower_serial": "Numer seryjny kosiarki",
                    "mower_name": "Nazwa kosiarki"
                },
                "description": "Proszę wybrać numer seryjny kosiarki Bosch którą chcesz dodać"
            }
        }
    }
}
```

**Comment by wimb0** [comment]
@zmechu I've added your pl.json to my pull request.

**Comment by jm-73** [comment]
I have included the PR wich translates the config flow. If anyone wants to include the possibility to translate the whole integration, please make a PR to the devlop branch.
