### ISSUE TITLE
Indego dischraging rapidly when Docked with Single Key Login Integration

### ISSUE THREAD

**Issue by HAuser1234** [jm-73/Indego#181]
With the new Integration my Indego very rapidly looses Power. I suspect the integration polling it way too often!
![grafik](https://github.com/jm-73/Indego/assets/122117318/14ac6c13-ca53-406d-8c5d-7e670de3b8a5)

Is there a way to adjust the polling rate?

**Comment by Shamshala** [comment]
Have you tried it with the integration disabled? Because the polling should be made againts the Bosch server, not a mower itself.

**Comment by jm-73** [comment]
No way to adjust the polling rate. In the beginning of the integration I used direct polling to the mower that woke the mower up.
Later versions has been improved with telling the server each 600 seconds (I think) "if something happends please tell the integration". Regardless it shouldnt keep your mower awake.
Please try with the integration diabled. If it not helps, send logs with debug enabled.

**Comment by HAuser1234** [comment]
ok interesting. Has anyone seen the same issue? maybe I just switch it on and off and see if the issue persits.
Also I will try disabling the integration!

**Comment by maciek188** [comment]
shortly after managing the integration into HA I got:
![Screenshot 2023-05-24 232000](https://github.com/jm-73/Indego/assets/96416174/e200aec2-465c-4bf0-8b0f-13c215033a56)
Indego 350
Device info
3600HB0100
by Bosch
Firmware: 27357.01251

**Comment by maciek188** [comment]
![image](https://github.com/jm-73/Indego/assets/96416174/cea04f88-074b-40a4-938b-2f0be7edaf18)
