### ISSUE TITLE
Lost Connection since new Android App

### ISSUE THREAD

**Issue by parkkralle** [jm-73/Indego#184]
Since the release of the new Android App V4.0.2 I have lost my connection via Homeassistant. So I deleted the integration and wanted to reconnect. But now I get the message "No mowers found in this Bosch Indego Account". I have installed the Chrome extension. Do you guys have any idea?

**Comment by LarsLautrup** [comment]
The integration stopped working a couple of days ago. Apparently due to some restrictions on the user-agent value of the request to the Bosch API.

https://github.com/jm-73/pyIndego/issues/119

I have not been able to find the setting in the integration, so I don't know how to fix it.

**Comment by clfberlin** [comment]
Oh, ok. Too bad. But thanks!

**Comment by jm-73** [comment]
We are waiting for pull requests. A solution exists but it has to be included in a new release.

**Comment by jm-73** [comment]
See the workaround mentioned in pyIndego.
