### ISSUE TITLE
Single ID Change

### ISSUE THREAD

**Issue by Eckart0** [jm-73/Indego#185]
Hi,

I have changed my Bosch Single ID account. 

Now I cannot install this Indego integration. It fails with the message "Bosch Indego Mower
No mowers found in this Bosch Indego account!" Probably uses the integratin uses the old Bosch account.

I have installed the chrome extension. It brings me directly to the old account and I have no chance to renew the mail adress and the passwort of my new account.

How can I enter the mail adress and the passwort of my account?

Regards,
Eckart

**Comment by LarsLautrup** [comment]
Check the settings in secrets.yaml

**Comment by clfberlin** [comment]
Odd. I have the same problem. No entry in secrets.yaml. Would you happen to have an example for the configuration so I know the syntax? Thanks!

**Comment by jm-73** [comment]
Reinstall the integration?
Reinstall HA?

**Comment by jm-73** [comment]
Clear cache?

**Comment by clfberlin** [comment]
Thanks. I tried it on several PCs, so cache shouldn't be the integration. But I'll try the install. I have a seperate test installation.

**Comment by clfberlin** [comment]
Same behavior on different HA installation. Well, I guess I'll just wait patiently. Thanks!

**Comment by clfberlin** [comment]
Ah, sorry. My mistake. I just edited manifest.json with
`  "requirements": ["#pyIndego==2.2.2"],`
I then realized that @sander1988 had linked the correct entry.
  `"requirements": ["git+https://github.com/sander1988/pyIndego.git#pyIndego==2.2.2"],`
This works! Great! Thanks!

**Comment by Eckart0** [comment]
It dosen't word even with the new version.
I can't enter the Bosch Single ID mailadress and passwort, but am directly connected to an old Bosch account. I don't know, where in HA the login data are stored.
Regards,
Eckart

**Comment by jm-73** [comment]
Reinstall HA
