### ISSUE TITLE
"No mowers found in this Bosch Indego account!"

### ISSUE THREAD

**Issue by zmechu** [jm-73/Indego#186]
Component works fine, but few days ago it seems to not-refreshing data (mower under HA was "offline". In logs: 
```
Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alms/.../state?longpoll=true&timeout=300&last=64513' failed with HTTP status code: 502
502, message='Bad Gateway', url=URL('https://api.indego-cloud.iot.bosch-si.com/api/v1/alms/.../state?longpoll=true&timeout=300&last=64513'): Failed GET to Indego, won't retry

Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alms/.../state?longpoll=true&timeout=300&last=64513' failed with HTTP status code: 500
500, message='', url=URL('https://api.indego-cloud.iot.bosch-si.com/api/v1/alms/.../state?longpoll=true&timeout=300&last=64513'): Failed GET to Indego, won't retry
```
and a lot of:
```
Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alms/..../state?longpoll=true&timeout=300&last=260' failed with HTTP status code: 403
403, message='Forbidden', url=URL('https://api.indego-cloud.iot.bosch-si.com/api/v1/alms/.../state?longpoll=true&timeout=300&last=260'): Failed GET to Indego, won't retry
```
So, remove all mower entity, remove component, remove Chrome extension. After that install component, install Chrome extension and while installing Bosch Indego Mower integration got only "No mowers found in this Bosch Indego account!". But there is my mower in Bosh Indego account. In logs still "403 Forbriden" message:
`403, message='Forbidden', url=URL('https://api.indego-cloud.iot.bosch-si.com/api/v1/alms'): Failed GET to Indego, won't retry`

How to deal with it? :-)

**Comment by Daniel-Peeeh** [comment]
same for me. stopped working somewhen last week and now gives a "No mowers found in this Bosch Indego account!".

**Comment by PeterGT56** [comment]
same for me, No mowers found in this Bosch Indego Account.

**Comment by massive** [comment]
My guess is this https://github.com/jm-73/pyIndego/issues/119

**Comment by geppo81** [comment]
same for me, No mowers found in this Bosch Indego Account.

**Comment by NJ-89** [comment]
Also for me: "No mowers found in this Bosch Indego Account."

**Comment by randomfrankie** [comment]
same here. Component stopped working 2 weeks ago or so. Tried a new install and get the same result as the previous poster.

**Comment by jm-73** [comment]
My guess:
You flood your account with API calls. When you fix the integration with the workarounds posted in the bug mentioned above your account starts working again.
I hope @sander1988 will make a PR soon so we can solve this in the integration.

**Comment by geppo81** [comment]
> My guess is this [jm-73/pyIndego#119](https://github.com/jm-73/pyIndego/issues/119)

Now it's working for me! thanks!

**Comment by zmechu** [comment]
I think it doesn't work for me... All I have:
`Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:548
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 20:33:22 (1 occurrences)
Last logged: 20:33:22
/store return code 500`
and 
`Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:125
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 20:33:22 (1 occurrences)
Last logged: 20:33:22
Failed to to call /store -`
Also, there is no integration available in Config.
My manifest.json:
`{
  "domain": "indego",
  "name": "Bosch Indego Mower",
  "config_flow": true,
  "documentation": "https://github.com/jm-73/Indego",
  "dependencies": ["application_credentials"],
  "codeowners": ["@jm-73", "@eavanvalkenburg", "@sander1988"],
#  "requirements": ["pyIndego==3.0.1"],
  "requirements": ["git+https://github.com/sander1988/pyIndego.git#pyIndego==2.2.2"],
  "iot_class": "cloud_push",
  "version": "5.1.0",
  "loggers": ["custom_components.indego", "pyIndego"]
}`

**Comment by Eckart0** [comment]
It does not work for me. I have tried many things, but the result is always "No mowers found...".
I don't even know where I can enter/change the account or where my username/password are stored. I am occasionally redirected to a Bosch page with login via Single ID, but I can't enter anything there, instead I get directly to a window that tells me that there are no mowers in the account.

I'm giving up until there is a working intgretion again.

Or can I return to the old YAML version?

Greetings, Eckart

Attachment: Log-File

[230616 HA log Indego.txt](https://github.com/jm-73/Indego/files/11769969/230616.HA.log.Indego.txt)

**Comment by NJ-89** [comment]
> My guess: You flood your account with API calls. When you fix the integration with the workarounds posted in the bug mentioned above your account starts working again. I hope @sander1988 will make a PR soon so we can solve this in the integration.

The fixed metioned in the bug, also fixed it for me.

**Comment by BjarnePhaff** [comment]
I have the same problem, "No mowers found...". Where can I find the fix that some are mentioning?

**Comment by sander1988** [comment]
Looking at the logs I would guess it's caused by and solved with https://github.com/jm-73/pyIndego/issues/119 .

**Comment by jm-73** [comment]
I think the integration should work (without hacks to replace the pyIndego) with the latest beta release. 5.2.0.

**Comment by urbatecte** [comment]
Work like a charm 👍
Many thanks ✌️
________________________________

**Comment by zmechu** [comment]
Develop version seems to be working fine!
