### ISSUE TITLE
Block on adding integration

### ISSUE THREAD

**Issue by evilz** [jm-73/Indego#191]
Hello,

HA is blocked on this screen forever
![image](https://github.com/jm-73/Indego/assets/2937862/4a319b12-ee6a-4be6-8186-1eb5ecd0bce8)

Any idea ?

Thank

**Comment by 35aportal** [comment]
Hello, I'm having issued with the Indego integration after updating to HA 2023.8.0 - all was OK before the upgrade.

I had a trace back like that captured in #187 so I followed the thread and deleted my integration & reinstalled. After adding the integration, I needed to visit an external website where I added my SingleKey ID, but am now stuck on a page asking "Please wait...". Here we stay with nothing seemingly happening.

Any ideas on how to fix this? Thanks in advance.

**Comment by 35aportal** [comment]
I should add that I'm using Chrome as mentioned in the instructions.

**Comment by evilz** [comment]
Oh I got this now 
![image](https://github.com/jm-73/Indego/assets/2937862/08043c2b-5c75-4256-9dc3-26cb488ea0e8)

**Comment by Huvie91** [comment]
Same issue here.

**Comment by Huvie91** [comment]
Issue tend to be a mistake: forgot to activate IPv4 and ipv6 in the WiFi settings of HA.
