### ISSUE TITLE
fails to set up

### ISSUE THREAD

**Issue by nrpetonr** [jm-73/Indego#192]
since few days, it stopped working. specifically says FAILED TO  SET UP. nothing in logs, it used to work w/o any problem. i am on v 5.2.1. no problem to operate mower via bosch app. anyone else having problem?

**Comment by urbatecte** [comment]
Same here.
I've tried to remove Addon then reinstall it but then the link to bosh page Ask for credential (same as app), but next screen IS black and juste Ask for waiting...
