### ISSUE TITLE
Indego fails after update to HA 2023.08

### ISSUE THREAD

**Issue by 35aportal** [jm-73/Indego#193]
My Indego integration failed after updating HA, so I deleted the integration and reinstalled. After a few hiccups (I'd removed the helper from Chrome), the integration installed without errors, but has "No devices or entities". 

My log file shows...

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:619
Integration: Sensor (documentation, issues)
First occurred: 21:50:28 (4 occurrences)
Last logged: 21:52:32

Error adding entities for domain sensor with platform indego
Error while setting up indego platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial_number'

Let me know if anything else is needed to help debug this. Thanks in advance for your help.

**Comment by Helskov** [comment]
As a temporary solution comment out line 393 (Serial_number) in Custom_components>Indego>_init_.Py

        device_info = DeviceInfo(
            identifiers={(DOMAIN, self._serial)},
            #serial_number=self._serial,
            manufacturer="Bosch",
            name=self._mower_name,
            model=generic_data.bareToolnumber if generic_data else None,
            sw_version=generic_data.alm_firmware_version if generic_data else None,

Saw a similar problem with EUFY with similar workaround. 
https://github.com/fuatakgun/eufy_security/issues/855

**Comment by dvdmaz** [comment]
Hello, 
I have the same problem, the workaround also worked for me.
Thanks!

**Comment by antoinevandenhurk** [comment]
It worked for me too!

**Comment by RockFlare** [comment]
Confirming that this worked for me too.

**Comment by jm-73** [comment]
This fix is included in 5.3.0 (Beta)
