### ISSUE TITLE
Syntax changed

### ISSUE THREAD

**Issue by Vector-Int13** [jm-73/Indego#199]
Something's probably changed in the communication protocol. Already working intergration started reporting this. The newly added mower is not loading any entities. The original mower does not update their status and does not work.

TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial_number'
2023-09-13 11:15:02.202 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up indego platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(

**Comment by ramirahikkala** [comment]
I'm encountering the same issue. Interestingly, the Bosch Indego Connect Android app has also stopped working around the same time and can't connect to the mower. I'm not sure if these problems are related.

**Comment by jm-73** [comment]
It works for me today. I havent had the opportunity to test this last week. Is it still problem for you?
What version are you running of the plugin?
HA version?

**Comment by sytchi** [comment]
I've had the same problem and it was gone within 2 days. Everything seems fine now. Probably some issue on the Bosch side

**Comment by Vector-Int13** [comment]
> I've had the same problem and it was gone within 2 days. Everything seems fine now. Probably some issue on the Bosch side
A new version  5.4.0 has been released and the problem is gone.
Thanks to the developers!

**Comment by Vector-Int13** [comment]
A new version  5.4.0 has been released and the problem is gone.
Thanks to the developers!

**Comment by sytchi** [comment]
Actually I've never updated and still the problem disappeared
