### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by jjanderson** [jm-73/Indego#2]
Hi,

Again, really awesome work! Thanks very much. Do you recon, when you feel comfortable, that you can add this to HACS? Would just make keeping it updated easier..

Thanks again! Good Job!

**Comment by jm-73** [comment]
Hello! Of course I will do that. I dont know when, but it is comming! 
Thanks for the input!

**Comment by jm-73** [comment]
HACS integration is included in the next release.

**Comment by jm-73** [comment]
Can be found under "Bosch Indego Mower" in HACS store.
