### ISSUE TITLE
Indego map is missing

### ISSUE THREAD

**Issue by MartinKuhl** [jm-73/Indego#201]
I for some weeks now the new garden map is not working.
Just after the release it was working for me, but in the last couple of weeks I just get the information, that the map is unavailable:
<img width="1046" alt="image" src="https://github.com/jm-73/Indego/assets/55736453/8b48c993-0bee-470b-9c46-ff990a431f6c">

**Comment by Pr0mises** [comment]
Map entity got removed again in 5.4.0 [#182](https://github.com/jm-73/Indego/pull/182) due to missing testing as well as the other new features.

**Comment by MartinKuhl** [comment]
for me the map was working very well.

**Comment by Pr0mises** [comment]
It did but just read through the last comments in the PR and you'll understand the decision

**Comment by jm-73** [comment]
Thank you for understanding. If possible, contact the code owner to help with development if the map functions.
Closing issue.
