### ISSUE TITLE
`indego.delete_alert_all` doesn't work

### ISSUE THREAD

**Issue by Vitani** [jm-73/Indego#207]
When trying to call the delete/read alert services, I get an HTTP error 409 (_The HTTP 409 Conflict response status code indicates a request conflict with the current state of the target resource_)

```yaml
service: indego.delete_alert_all
data:
  alert_index: 0 # also tried 1
```

> Logger: pyIndego.indego_base_client
> Source: runner.py:188
> First occurred: 10:13:38 (18 occurrences)
> Last logged: 10:13:48
> 
> - Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alerts/{redacted}' failed with HTTP status code: 409
> - Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alerts/{redacted}' failed with HTTP status code: 409
> - Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alerts/{redacted}' failed with HTTP status code: 409
> - Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alerts/{redacted}' failed with HTTP status code: 409
> - Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alerts/{redacted}' failed with HTTP status code: 409

Dismissing the Bosch app on my phone and reloading it appears to clear the error, but then calling the service doesn't delete any of the alerts.

**Comment by kimzeuner** [comment]
Unfortunately i can not reproduce the failure. Just tested the function in my setup and everything works well. Is everything else working ? My whole integration was not working after i reconncted my indego today so i had to remove the component and add it again (maybe because my token expired as mentioned in #206 ), thats why i`m asking if everything else is working.

**Comment by Vitani** [comment]
I tried it again this morning after forcing an alert and it worked perfectly, I wonder if it was because I had hundreds of alerts previously, and after clearing them manually in the official Bosch app (that took AGES) it did something to make this work.

**Comment by sytchi** [comment]
Had an identical issue last year. I have it again now - if there is 'a lot of' alerts, deleting them through integration is not working. You have to do it manually through the app. After that everythig is back to normal. 

Maybe it's worth noting in "known bugs" along with the info on alerts
