### ISSUE TITLE
Status: Cleaning

### ISSUE THREAD

**Issue by 1192410** [jm-73/Indego#218]
Hello, 

not sure if its a feature or a bug. But the mower shows stauts cleaning and in the details mowing. Could that be changed to the same status mowing throughout the integration ? 

![image](https://github.com/jm-73/Indego/assets/73297737/df791297-3092-4cdf-947a-feeadb26eb44)

**Comment by sander1988** [comment]
That's expected in the current release as it's using a vacuum type withing HA. So HA translates the active state to 'cleaning'.

The lawn mower entity is only available in HA for a few months now, so not yet integrated in the the current release. Note that the lawn mower entity type is already available on the develop branch of this component.

**Comment by 1192410** [comment]
Thank you very much for the quick reply and clarification. I really
appreciate your work.

Best regards, Andreas

Sander Peterse ***@***.***> schrieb am So. 26. Mai 2024 um
15:46:
