### ISSUE TITLE
Add develop version to HACS

### ISSUE THREAD

**Issue by adi90x** [jm-73/Indego#220]
Hello,

Quick question, is there a way to add develop branch to HACS ? Maybe under beta version ?

Regards,

**Comment by jm-73** [comment]
I have published a beta when I wanted to test. It is the most simple solution I think.Kind regards Jens Mazzanti-Myretyr27 maj 2024 kl. 18:19 skrev adi90x ***@***.***>:﻿
Hello,
Quick question, is there a way to add develop branch to HACS ? Maybe under beta version ?
Regards,

**Comment by sander1988** [comment]
I have never used HACS myself, but I have created the pre-release v5.7.0b0. You should enable beta versions based on the [docs](https://hacs.xyz/docs/faq/beta/).

Are you able to install it?

**Comment by adi90x** [comment]
Hello,

Thanks a lot, seems to be working as expected I have just install 5.7.0b0


Regards,
