### ISSUE TITLE
Update and add translations

### ISSUE THREAD

**Issue by sander1988** [jm-73/Indego#221]
We should update translations due to new functionality and we can add some more languages (when by provided). There was already some discussing in PR #216.

- [x] Update DE - Config and indego_alert items missing
- [x] Update PL - Config and indego_alert items missing
- [x] Add FR translations

**Comment by zmechu** [comment]
[pl.json](https://github.com/jm-73/Indego/files/15476219/pl.json)
PL translation

**Comment by sander1988** [comment]
@zmechu - Thank you for your contribution. The file doesn't seem to match the latest format (please see the EN file). Can you check and update your translation?

**Comment by zmechu** [comment]
[pl.json](https://github.com/jm-73/Indego/files/15476427/pl.json)
Should be OK now :-) Please check if it fit.

**Comment by kimzeuner** [comment]
@zmechu i think you forgot the translations for the alert entity/attributes
```
    "entity": {
        "binary_sensor": {
            "indego_alert": {
                "state_attributes": {
                    "alerts_count": {
                        "name": "Number of alerts"
                    },
                    "last_alert_error_code": {
                        "name": "Error code (most recent)"
                    },
                    "last_alert_message": {
                        "name": "Alert message (most recent)"
                    },
                    "last_alert_date": {
                        "name": " Alert date (most recent)"
                    },
                    "last_alert_read": {
                        "name": "Alert status (most recent)",
                        "state": {
                            "read": "Read",
                            "unread": "Unread"
                        }
                    }
                }
            }
        }
    },
```

Here is the updated DE translation
[de.json](https://github.com/jm-73/Indego/files/15479313/de.json)

What do you think of also translating the mower state and mower state detail ? 
i`m using it in my system but i`m not sure if it is interesting for everyone ?!

**Comment by urbatecte** [comment]
@sander1988 
Hi there !
Please find the french translation.
[fr.json](https://github.com/jm-73/Indego/files/15479895/fr.json)

Thanks for all your work 👌

**Comment by zmechu** [comment]
> @zmechu i think you forgot the translations for the alert entity/attributes
Ups :-) I think use not up-to-date file. Please give me link to english file to translate,

**Comment by kimzeuner** [comment]
This is the latest en.json file [Link](https://github.com/jm-73/Indego/blob/684b9d752be39b9a8bf2079b55510ce801468e2f/custom_components/indego/translations/en.json)

**Comment by zmechu** [comment]
> This is the latest en.json file [Link](https://github.com/jm-73/Indego/blob/684b9d752be39b9a8bf2079b55510ce801468e2f/custom_components/indego/translations/en.json)

[pl.json](https://github.com/jm-73/Indego/files/15490917/pl.json)
now should be OK :-)

**Comment by obi134** [comment]
Hi @sander1988 ,
Thank you for your effords. Please check following PR #222 
Best regards

**Comment by sander1988** [comment]
Thank you everyone for your contribution! It has been merged and is available at the develop branch.
