### ISSUE TITLE
The connection to the Bosch Indego API failed!

### ISSUE THREAD

**Issue by mirkin-pixel** [jm-73/Indego#223]
After the update, my integration did not load. When I want to add the mower again and go through all the steps and come back to Home Assistant I get the message: The connection to the Bosch Indego API failed!

What could be causing this problem?

**Comment by zmechu** [comment]
I think there is User-Agent issue, Bosch "blocking" HomeAssistant devices.  Try to use other User-Agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 14_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/126.0 Mobile/15E148 Safari/605.1.15" (Firefox on Iphone) helps for me :-)

**Comment by mirkin-pixel** [comment]
> I think there is User-Agent issue, Bosch "blocking" HomeAssistant devices.  Try to use other User-Agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 14_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/126.0 Mobile/15E148 Safari/605.1.15" (Firefox on Iphone) helps for me :-)

Thanks @zmechu This solved the problem

**Comment by gohlas** [comment]
Had same issue, also solved mine!
Thanks

**Comment by WhyLev** [comment]
🤖 **AI Summary of the solution:**

The connection issue to the Bosch Indego API was resolved by changing the User-Agent to a specific Firefox on iPhone string.
