### ISSUE TITLE
HTTP error 403 since 5.7.0b1

### ISSUE THREAD

**Issue by parkkralle** [jm-73/Indego#225]
Since version 5.7.0b1, the integration can no longer register with the API. I now always get an HTTP Error 403 in the log. Reinstalling the integration and registering again via the Chrome plugin does not work either. I'm attaching a screenshot.

![Screenshot 2024-06-03 101611](https://github.com/jm-73/Indego/assets/59173472/df11ad7d-50e8-4e58-99e5-41790cc55580)

**Comment by Albert994** [comment]
I also got an API error. For me it helped to change the name of the user agent in the configuration dialog.

**Comment by mrtobs1** [comment]
Where did you change what name? Thanks for your help.

**Comment by nrpetonr** [comment]
similar problem for me. using  chrome extension ends up with error "The connection to the Bosch Indego API failed". it started after updating to v 5.7.0b1

**Comment by kimzeuner** [comment]
> Where did you change what name? Thanks for your help.

You can change the User-Agent in Devices & services --> Bosch Indego Mower Integration --> Configure (right side next to your mower)

For me the default User-Agent didn`t work too so i just changed it to "The name of my mower Indego"
