### ISSUE TITLE
Mower unavailable in version 5.7.0b1

### ISSUE THREAD

**Issue by wimb0** [jm-73/Indego#226]
## Checklist

- [X] I have updated to the latest available of the Indego component version.
- [X] I have updated to the latest available Home Assistant version.
- [X] I have read the readme and checked for other open or recently closed issues for similar bugs/issues.

## The problem

The latest beta version 5.7.0b1 does not seem to work.
Most entities are not available.
Bosch Indego App works fine.
Changing the UserAgent does not help.

## Environment

- Indego component release with the issue: 5.7.0b1
- Last working Indego component release (if known): 5.7.0b0
- Home Assistant release with the issue: 2024.5.5
- Last working Home Assistant release (if known): 2024.5.5
- Operating system: Supervised on Debian 12

## Logs

I get the following error in the logs:
  ```
Deze fout is ontstaan door een aangepaste integratie.
Logger: custom_components.indego
  Bron: custom_components/indego/__init__.py:542
  integratie: Bosch Indego Mower (documentatie)
  Eerst voorgekomen: 2 juni 2024 om 19:41:00 (2406 gebeurtenissen)
  Laatst gelogd: 11:53:37
  
  Mower state update failed, reason: 'IndegoAsyncClient' object has no attribute 'online'
```

## State of relevant entities

![image](https://github.com/jm-73/Indego/assets/11030068/38d4fc35-7ad7-4693-9aa7-b5c1c10f81ec)

**Comment by kimzeuner** [comment]
Having the same issue. For me the latest working version is 5.7.0b0

**Comment by wimb0** [comment]
Just checked, 5.7.0b0 is also still working for me.

**Comment by sander1988** [comment]
Somehow HA did not update to the latest pyIndego version here. This is probably the result of using/testing beta versions (which is not supported by HA and therefore only recommended for advanced users).

The fix here is to remove the pyIndego pip and restart HA, that should trigger the reinstall (and your should see it in the logs).

**Command to remove pyIndego for Docker based installs:**
`pip uninstall pyIndego`

I don't know the command for other type of installs.

You should remove the old alert entities manually; HA shows a notification icon about that in the entities screen.

**Comment by wimb0** [comment]
@sander1988 thanks for the info.
This fixed the problem for me :-)
I use Home Assistant supervised, and the solution is simple:
SSH to the host, run `docker exec -it homeassistant sh` to get in the container, then run `pip uninstall pyIndego`
![image](https://github.com/jm-73/Indego/assets/11030068/df094dbc-705e-4b8a-8529-b61d397a60f9)

**Comment by sander1988** [comment]
@wimb0 - Thank you for confirming. And note that the version of pyIndego gets bumped after beta, so that will prevent this issue on the final release.
