### ISSUE TITLE
Die Verbindung zur Bosch Indego API ist fehlgeschlagen!

### ISSUE THREAD

**Issue by felixhohlstein** [jm-73/Indego#227]
Nach dem neustem Update lässt sich leider keine Verbindung mehr aufbauen.

Nach Versuch den Mower über Api einzurichten erscheint folgende Fehlermedung:

Die Verbindung zur Bosch Indego API ist fehlgeschlagen!

Ist dies ein bekanntes Problem oder bin ich da der Einzige?

**Comment by kimzeuner** [comment]
Meinst du mit dem neusten Update eine der Beta Versionen 5.7.0b0 /5.7.0b1 /5.7.0b2 ?
Du kannst unter Geräte und Dienste --> Bosch Indego Mower --> Rechts neben deinem Mäher auf konfigurieren den User-Agent einstellen. ie Bosch API hat scheinbar ein Problem damit, dass standardmäßig HomeAssistant darin vorkommt. Ich habe den User Agent einfach auf "Name meines Mähers Indego" umgestellt, danach funktionierte es wieder.

**Comment by felixhohlstein** [comment]
> Meinst du mit dem neusten Update eine der Betaversionen 5.7.0b0 /5.7.0b1 /5.7.0b2? Sie können unter Geräte und Dienste --> Bosch Indego Mower --> Rechts neben Ihrem Mäher auf die Konfiguration des User-Agents einstellen. Die Bosch API hat scheinbar ein Problem damit, dass HomeAssistant standardmäßig darin vorkommt. Ich habe den User Agent einfach auf "Name meines Mähers Indego" umgestellt, danach funktionierte es wieder.
> 
> Wenn dein Rechner noch nicht eingerichtet ist, wird der User-Agent glaube ich auch im Einrichteprozess abgefragt, dann einfach da schon ändern.

Ja, genau!

Super, hat geklappt, vielen Dank für deine Hilfe!

Wünsche dir ein schöne Wochenende.

**Comment by felixhohlstein** [comment]
Gelöst

**Comment by bertrijken** [comment]
I've been struggling with this API Failed situation for months, and seems the solution is that simple! Thank you for helping me reenable my Indego :-)

**Comment by nagi121** [comment]
It would be very helpful to mention the solution (changing the user agent) at README.md.

**Comment by kimzeuner** [comment]
It already is part of the readme, see chapter "Known issues"

**Comment by nagi121** [comment]
That's right. 
As part if the configuration section, it would prevent the trial and error steps.
Much better would be to remove the default value during first time installation.

**Comment by WhyLev** [comment]
🤖 **AI Summary of the solution:**

The issue with connecting to the Bosch Indego API was resolved by changing the User-Agent in the configuration settings.
