### ISSUE TITLE
Connexion API

### ISSUE THREAD

**Issue by Larnak23** [jm-73/Indego#229]
I updated the last version today and try to integrate my Indego. I used Chrome with the extension : HomeAssistant Indego authentication.

A new page is open and I am able to introduce my login and password, to choose Indego as a mower and after I receive the message "La connexion à l'API Bosch Indego a échoué !"

Thanks for your help

**Comment by user45876** [comment]
According to other issues here (closed ones) and my own experience today ;) you should just change the User Agent in the Integration Configuration to something else - preferrably not containing 'HomeAssistant'.

I am quite furious that Bosch has the guts to actively block their customers who pay the show...

**Comment by Larnak23** [comment]
Thank you, unfortunately I dont remember how to change the user agent, I installed it several months ago. Is there any tutto how to create a new API

**Comment by Larnak23** [comment]
Perfect it works

**Comment by user45876** [comment]
You are welcome. Would you mind closing the issue?

**Comment by Larnak23** [comment]
Thks for all

**Comment by WhyLev** [comment]
🤖 **AI Summary of the solution:**

The issue with the Indego API connection was resolved by changing the User Agent in the Integration Configuration to something that does not include 'HomeAssistant'.
