### ISSUE TITLE
HTTP 403 error after update 5.7

### ISSUE THREAD

**Issue by arnoakavdb** [jm-73/Indego#231]
After updating to the latest version i'm facing issues with my mower --|> no more accessible and when i try to re add it i'm facing issue 

![image](https://github.com/jm-73/Indego/assets/38015866/43643e6e-b134-472b-bdd3-8ae297d6bbc5)

everything was working fine with 5.6 version

**Comment by defuuss** [comment]
I just wanted to create a ticket and saw you created one , have the same error and the same problem .

**Comment by kimzeuner** [comment]
Did you already try to change the User-Agent as described in several closed issues ?

**Comment by defuuss** [comment]
Yeah stupid me , just change in the integration the User-Agent  and everything is working

**Comment by arnoakavdb** [comment]
Thank you for pointing this I search about the update but I found nothing.now everything is running fine

**Comment by NJ-89** [comment]
This fix also worked for me!

**Comment by bmause** [comment]
Ich habe noch Probleme mit der Weiterleitung nach der Anmeldung von Single key ![image](https://github.com/jm-73/Indego/assets/105861086/ba073fd7-d296-4057-ad14-6fab4ca8a074)

**Comment by kimzeuner** [comment]
I would say you are using the wrong browser as it says "Safari kann die seite nicht öffnen". It obly works with the chrome browser (and dont forget to install the extension before)

Ich denke du benutzt den falschen Browser. Du musst den Chrome Browser benutzen und nicht vergessen vorher die Chrome Erweiterung zu installieren.

**Comment by Stargate4848** [comment]
Selbst mit dem Chrome Browser mit der Chrome Erweiterung gelingt die erneut nötige Aktivierung der Version 5.7 über Bosch SingleKey nicht.

**Comment by kimzeuner** [comment]
What do you mean with "activating it"? Which failure occurs ? Is it the same as in the screenshot by bmause ? 
Do you have an error in your HA Logs ?

**Comment by Stargate4848** [comment]
> What do you mean with "activating it"? Which failure occurs ? Is it the same as in the screenshot by bmause ? Do you have an error in your HA Logs ?


After Update from 5.5.0 -> 5.7.0 and restart HA:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: pyIndego.indego_base_client
Quelle: custom_components/indego/__init__.py:743
Integration: Bosch Indego Mower (Dokumentation)

Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alms/603702617/state?longpoll=true&timeout=300&last=258' failed with HTTP status code: 502

Mower state update failed, reason: 502, message='Bad Gateway', url=URL('https://api.indego-cloud.iot.bosch-si.com/api/v1/alms/603702617/state?longpoll=true&timeout=300&last=258‘)

Mower unusable in HA
Back to 5.5.0 and it works fine as before.

**Comment by sander1988** [comment]
See known issues regarding 4XX and 5XX errors: https://github.com/jm-73/Indego?tab=readme-ov-file#known-issues

It's normal for their endpoints to see these some time to time. If you see them continuously please open a new issue following the issue template. It's impossible to debug these can of issues when issues don't contain the minimum required information.

**Comment by WhyLev** [comment]
🤖 **AI Summary of the solution:**

The HTTP 403 error experienced after updating to version 5.7 was resolved by changing the User-Agent in the integration settings.
