### ISSUE TITLE
Die Verbindung zur Bosch Indego API ist fehlgeschlagen!

### ISSUE THREAD

**Issue by Kloenner** [jm-73/Indego#233]
Hallo,
I add the integration through the HomeAssistant interface (Settings > Devices & Services > Add Integration), i get the Error " Die Verbindung zur Bosch Indego API ist fehlgeschlagen!"

Greeting 

HD

**Comment by kimzeuner** [comment]
Have you already changed the user agent ? There are many issues from the last days that describe this issue

**Comment by Kloenner** [comment]
what do you mean by user agent?, the integration "Bosch Indego Mower", , I have renewed this

**Comment by Kloenner** [comment]
the integration "Bosch Indego Mower" did not install under Integration, because after authorize on the Bosch Website there come the Error "Die Verbindung zur Bosch Indego API ist fehlgeschlagen!"

**Comment by kimzeuner** [comment]
And you have changed the user agent in this screen to anything without homeassistant ?!

**Comment by Kloenner** [comment]
Oh, now i understand, i have change the name of the user agent and now it is ok

many thanks to you for helping :)

**Comment by crusherweb** [comment]
I can confirm. You need to change also the User-Agent when you freshly install the addon.

After Changing the name it was possible to add the mower.

**Comment by kimzeuner** [comment]
@Kloenner can you close the issue as it is solved ?

**Comment by WhyLev** [comment]
🤖 **AI Summary of the solution:**

The issue with the Bosch Indego API connection failure was resolved by changing the User-Agent in the browser settings during installation.
