### ISSUE TITLE
After Update/Re_Install version 5.7.0: "The connection to the Bosch Indego API failed" (like #231)

### ISSUE THREAD

**Issue by stbuerger** [jm-73/Indego#235]
After update 5.7.0 from within HA entities became unavailable.
Reloading integration from HA showed missing entry.
Re-Installing integration launches browser addon, but after succesfull completing authentication HA presents a pop-up window with the information "The connection to the Bosch Indego API failed".

.. like in #231 ..

From home-assistant.log:
```
2024-06-22 09:45:37.944 INFO (MainThread) [custom_components.indego.config_flow] Successfully authenticated
2024-06-22 09:45:42.841 ERROR (MainThread) [pyIndego.indego_base_client] [8ED825] Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alms' failed with HTTP status code: 403
2024-06-22 09:45:42.841 ERROR (MainThread) [custom_components.indego.config_flow] Error while retrieving mower serial in account! Reason: 403, message='Forbidden', url=URL('https://api.indego-cloud.iot.bosch-si.com/api/v1/alms')
```

**Comment by kimzeuner** [comment]
And did you already change the user agent as mentioned in your linked issue and many others ?

**Comment by stbuerger** [comment]
> And did you already change the user agent as mentioned in your linked issue and many others ?

When/while re-installing the integration, I can't get into the configuration dialog to do that.
Can I somehow change this in the code - right afterdownload and before adding/starting the integration ?

I'm lost too in how to download/install older versions with the new HA(CS) GUI.

**Comment by stbuerger** [comment]
> > And did you already change the user agent as mentioned in your linked issue and many others ?
> 
> When/while re-installing the integration, I can't get into the configuration dialog to do that. Can I somehow change this in the code - right afterdownload and before adding/starting the integration ?
> 
> I'm lost too in how to download/install older versions with the new HA(CS) GUI.

After 5 attempts it worked **WITH CHANGED USER AGENT**
Interesting issue in my casse: The dialog with entries for "User Agent" - "expose as Mower" - etc did no longer appear after the 1st re-installation.
What seemed to change this, was to manually remove the complete `config/custom_components/indego` subdirectory

**Comment by kimzeuner** [comment]
Glad to your you solved it. Just to answer your question: you can go (back) to another version with going into HACS - click on the integration - 3 dots in upper right corner - there should be something like re-download or download again (not sure how it is named in english version) - choose the version you want from the drop down menu

**Comment by WhyLev** [comment]
🤖 **AI Summary of the solution:**

The issue with the Bosch Indego API failure was resolved by changing the user agent during reinstallation and removing the existing integration files, allowing the configuration dialog to appear.
