### ISSUE TITLE
Instalation error API

### ISSUE THREAD

**Issue by n4rs** [jm-73/Indego#236]
I know API error is a knows issue when updating for what I saw here, problem is I'm doing a fresh install, never had it before, and I can't even get passed the menu where it asks me to define as a mower or a vacuum. As soon as it passes that menu it gives API error, so I can't change the user_agent that's in the know issue, since I can't access the configs for it.

**Comment by kimzeuner** [comment]
For another user it helped to delete the indego folder in custom components and then re-install it.

See issue [#236](https://github.com/jm-73/Indego/issues/235#issuecomment-2183949660)

**Comment by n4rs** [comment]
Already did it. The error stayed the same after reinstalling. The thing probably is that the other user was making an update. I am doing a new install. Is there another workaround?

**Comment by kimzeuner** [comment]
Did you restart ha between deleting the folder and re-installing ? 
Unfortunately i dont know another workaround. Maybe you can try to install version 5.5 or 5.6 first and then make the update ? 
Do you have any error logs so the developer can have a deeper look ?

**Comment by brononius** [comment]
I'm following. Getting the same behavior.

Removed it, (couldn't delete the folder, wasn't there) rebooted and reinstalled 5.7. 

Same with version 5.6.

**Comment by brononius** [comment]
Today, I was able to connect with 5.6.1 (and also 5.5).
But when I update towards 5.7, it starts failing.

[boschindego.log](https://github.com/user-attachments/files/16043639/boschindego.log)
`

**Comment by kimzeuner** [comment]
And did you already change the user-agent under "configure" in your integration ? If not, change it to anything without "HomeAssistant". The 403 error looks like it is not changed.

**Comment by brononius** [comment]
I´m not seeing a possiblity to change the user field.
  

  
KR
  
Ben
  

  

  

  

  
  
  
  
  
>

**Comment by kimzeuner** [comment]
Ok, just checked your screenshots again at compared it with my setup. It really seems as your integration is still on 5.5 so you will not be able to change the user agent as it was released with 5.7
Can you re-download version 5.7 by clicking on the three dots in the upper right corner (in hacs) and go to download again and select 5.7 ?

**Comment by brononius** [comment]
Had to remove it completely, reboot 2 times, and installed 5.7. But resulting in the same error again...

Then remove 5.7, install 5.6.1, everything goes fine. Upgrading to 5.7, restart HA, and getting back into troubles.
As you can see in the printscreen, no way to select another User-Agent. Only in 5.7.2, I've got another user-agent. But I can't select.

[
![Schermafdruk van 2024-07-01 08-04-10](https://github.com/jm-73/Indego/assets/22466675/260203e8-7ce2-4385-a3a2-11acf5ce267d)
](url)

![Schermafdruk van 2024-07-01 08-17-05](https://github.com/jm-73/Indego/assets/22466675/2ee47951-cad5-47c1-bfb3-0423e413d2ae)

Log file: 
[home-assistant_indego_2024-07-01T06-19-24.535Z.log](https://github.com/user-attachments/files/16048661/home-assistant_indego_2024-07-01T06-19-24.535Z.log)

**Comment by kimzeuner** [comment]
You can not select the text field and type in any other text ? That's strange and to be honest i have no idea why this happens.
Is the integration working with version 5.7.2 ? As the default user-agent was changed it should work.

**Comment by brononius** [comment]
No, once I upgrade to 5.7 (0, 1 or 2) integration is failing.
When I remove the node, and try to add it again, I'm getting the API 
code.

KR
B

kizeu schreef op 2024-07-01 08:41:

> You can not select the text field and type in any other text ? That's 
> strange and to be honest i have no idea why this happens.
> Is the integration working with version 5.7.2 ? As the default 
> user-agent was changed it should work.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you commented.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/jm-73/Indego/issues/236#issuecomment-2199357211
[2]

**Comment by brononius** [comment]
Ahhh, so the trick is to simply use another name for the User-Agent?
I thought you had to select (dropdown or so) something else...

Just typ in something you want, I entered for example Toby (name of my mower), and it works...

![image](https://github.com/jm-73/Indego/assets/22466675/5340345d-f7fb-4ed2-b7ae-15730c44059c)

**Comment by kimzeuner** [comment]
Yes, correct. Sorry if it was not clear in my explanations.
Glad to hear that it works now.

**Comment by WhyLev** [comment]
🤖 **AI Summary of the solution:**

The installation error was resolved by changing the User-Agent to a custom value that does not include 'HomeAssistant'.
