### ISSUE TITLE
Integration failed

### ISSUE THREAD

**Issue by eddieari** [jm-73/Indego#237]
Hi,

For some time now, my Indego integration has not been working. With the new integration I get the following errors: 
This error was caused by a custom integration.

Logger: pyIndego.indego_base_client
Quelle: custom_components/indego/config_flow.py:163
Integration: Bosch Indego Mower (Dokumentation)
Erstmals aufgetreten: 13:31:32 (3 Vorkommnisse)
Zuletzt protokolliert: 13:35:13

`'[F1CB43] Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alms' failed with HTTP status code: 403'
'[2A78C5] Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alms' failed with HTTP status code: 403'
'[BDD06C] Request to 'https://api.indego-cloud.iot.bosch-si.com/api/v1/alms' failed with HTTP status code: 403'`

Logger: custom_components.indego.config_flow
Quelle: custom_components/indego/config_flow.py:170
Integration: Bosch Indego Mower (Dokumentation)
Erstmals aufgetreten: 13:31:32 (3 Vorkommnisse)
Zuletzt protokolliert: 13:35:13

`Error while retrieving mower serial in account! Reason: 403, message='Forbidden', url=URL(https://api.indego-cloud.iot.bosch-si.com/api/v1/alms)`

I followed the instructions exactly for the integration. 

The following windows appeared:

<img width="603" alt="image" src="https://github.com/jm-73/Indego/assets/82974243/c4cebb07-2dd9-42f3-be46-5c607ea5bb87">

<img width="427" alt="Bildschirmfoto 2024-06-26 um 14 25 43" src="https://github.com/jm-73/Indego/assets/82974243/be36cf3d-9a87-45d6-b5ff-4db0f87bb2f3">

Home Assistant Verison:

<img width="597" alt="image" src="https://github.com/jm-73/Indego/assets/82974243/ed2fdeb0-dc36-4cd5-89c5-31cb60a201bf">

Thanks for support in advance!
Thomas

**Comment by kimzeuner** [comment]
Please change the user agent in your first screenshot to anything you want without "HomeAssistant" as it is described in many closed issues. And select if you want your mower to be shown as vacuum or lawn_mower entity.

**Comment by WhyLev** [comment]
🤖 **AI Summary of the solution:**

The issue with the Indego integration was resolved by changing the user agent to something other than 'HomeAssistant', as suggested in previous closed issues.
