### ISSUE TITLE
Alert entity

### ISSUE THREAD

**Issue by YoMan12** [jm-73/Indego#240]
I'd like to ask what is shown as the alert entity. To be precise I've got an m+ 700 for 2 years and always when I make the integration there was an entity called "Alert" and the state is "problem" - I thought it just must be in that way but ... yesterday I have installed m+500 and the entity Alert is "ok" so .... what could be wrong?
![image](https://github.com/jm-73/Indego/assets/42252155/666f7947-459f-4aee-a4dd-a7c5b7e72cb9)

**Comment by kimzeuner** [comment]
The Alert entity shows if there is an alert/error on your mower or not. As it is a binary sensor it shows ok when there is no alert and problem when there is an alert. Do you have any alert/error/notification in your bosch app for your m+700 ?

**Comment by YoMan12** [comment]
Nope, no alerts on the device.

**Comment by YoMan12** [comment]
I think that I misunderstood .... I thought that alert is about something now ... and it probably shows that there is an unread message alert in  the cloud :) 
Sorry for wasting time

**Comment by WhyLev** [comment]
🤖 **AI Summary of the solution:**

The user inquired about the 'Alert' entity state difference between two models (m+700 and m+500), leading to clarification that it indicates the presence of alerts/errors.
