### ISSUE TITLE
Component cant handle a mower that is offline

### ISSUE THREAD

**Issue by jm-73** [jm-73/Indego#32]
Some of the API calls is based on that the mower is contacted for an answer. The component cant handle this and crashes when no answer is recived.

**Comment by jm-73** [comment]
Will be fixed in 0.7.4

**Comment by Siggy101** [comment]
Hi @jm-73 
I see that you were planning this fix in v0.8.0 but the latest is still 0.7.4.  Is 8 in the pipeline?

**Comment by jm-73** [comment]
Fixed in 0.8
