### ISSUE TITLE
Next mowing time

### ISSUE THREAD

**Issue by Shamshala** [jm-73/Indego#39]
Hi, first of all, perfect job! May i have a question, do you plan to add something like a "Next mowing time"? That could be really helpful. Thank you so much!

**Comment by jm-73** [comment]
Next mowing time is a good idea. I havent had the time to implement it yet. I have just found out about a API call that may help us with this. But even in the Bosch App there are no such thing as next planned mowing. It is only a schedule that is published in the app.

**Comment by Shamshala** [comment]
Sadly, i'm missing such thing in the Bosch's app. Even more when i've noticed it is possible to show such info in more pleasing way: [http://grauonline.de/alexwww/indego/indego.html](http://grauonline.de/alexwww/indego/indego.html)

I'm not a programmer (mercy please) but isn't possible to show the closest schedule date? I assume there is only information about day of the week and hour so the actual date must be calculated.

**Comment by jm-73** [comment]
Yes, that is the plan. To calculate the next schedulet cuttiong session by looking at the schedule.

**Comment by jm-73** [comment]
Fixed in 0.8
