### ISSUE TITLE
Battery Life

### ISSUE THREAD

**Issue by pfriedrich84** [jm-73/Indego#49]
Hi,

it seems the battery is sucked empty. Any chance to change that?

BR, Paul

**Comment by Siggy101** [comment]
Indeed, the mower does not seem to sleep anymore.  My lifetime counter still increments 24/7 even when the mower is not mowing.

**Comment by pfriedrich84** [comment]
The problem is in the 1Min-Refresh Method the getOperationalData() this is holding the mower awake. 
@jm-73 it would be great to add a custom field for the refresh of the Mower-Data with this method. 
For example i don'T care about battery status and so on.

The 1h-Refresh is getting the Status from the BoschAPI (State Docked,Mowing also Alerts etc.) i think this would be enough!

**Comment by jm-73** [comment]
This is in the roadmap to fix. Pull requests are welcome! Will try to look into this this weekend!

**Comment by jm-73** [comment]
Fixed in 1.0
