### ISSUE TITLE
How to handle the state of the mower?

### ISSUE THREAD

**Issue by ltjessem** [jm-73/Indego#5]
>  As it is implemented now, the mower has almost 30 states. This doesnt look good in HA.

I agree, particularly the status of Docked vs Charging doesn't make much sense as I see it charging while "Docked" but sometimes the status will change to "Charging" seemingly at random. The Bosch app doesn't differentiate between these two statuses either, displays both as "Charging". 

Thinking about this, maybe it could be split into two sensors, they existing one and a "pretty" one.
Could be for example:
257-263, 64513: Docked
513-519, 769-776: Active/undocked
1537: Stuck

Others like software update and diagnostic mode can be kept as they're rare enough to not cause unnecessary disturbance in the history. The existing verbose sensor can be used for those who want a more detailed status.

**Comment by jm-73** [comment]
You have the same idea as I have. Seems logic to go that way!

**Comment by ltjessem** [comment]
Looking at the behavior for a while, status 64513 should probably not trigger any change in the "pretty" sensor, as it'll go to sleep if left idle in lawn for a while too.

**Comment by jm-73** [comment]
This is integrated in the next release (0.6)

**Comment by jm-73** [comment]
Release 0.6 released!
