### ISSUE TITLE
% lawn mowed no longer increasing

### ISSUE THREAD

**Issue by Siggy101** [jm-73/Indego#50]
I have this integration installed through HACS.  All has been working for over a year.
3 days ago, the % lawn mowed stopped at 75% and is not longer increasing.  Battery level and all other sensors seem to be going up and down as normal.

**Comment by Siggy101** [comment]
![image](https://user-images.githubusercontent.com/41893936/81681881-ce729180-9454-11ea-86eb-cae36c90ed4c.png)

**Comment by Siggy101** [comment]
![image](https://user-images.githubusercontent.com/41893936/81682100-ec3ff680-9454-11ea-8b93-5644d1ad171c.png)

**Comment by jm-73** [comment]
Strange! Have anyone else experienced this problem?

**Comment by Siggy101** [comment]
![Screenshot_20200520-230650_Home Assistant](https://user-images.githubusercontent.com/41893936/82497498-a3d8a680-9aee-11ea-8b6b-802d0877ec87.jpg)
Interestingly, it seems to have resolved itself after just under a week. 
It's now incrementing normally again. 
My suspicion is that Bosch were tinkering with the API as the app started doing sketchy things too. 
For now, I'd say there is nothing you need to do.

**Comment by jm-73** [comment]
Probably some Bosch API Server issue. Close this for now!
