### ISSUE TITLE
Unable to install v8 due to an incorrect Home Assistant version dependancy

### ISSUE THREAD

**Issue by Siggy101** [jm-73/Indego#55]
When trying to upgrade Indego via HACS, I have the following error message despite meeting the HA version requirement.
The HA version requirement is set to **1**.110.0 when I believe it should probably be **0**.110.0

![image](https://user-images.githubusercontent.com/41893936/83617750-d15f2e80-a589-11ea-9115-a2a3dbc3810a.png)

**Comment by bekkm** [comment]
As already mentioned in discord @jm-73 probably needs to publish the master to the 0.8 or 0.81 release.

**Comment by bekkm** [comment]
@Siggy101 Now it works with 0.8.1

**Comment by Siggy101** [comment]
Yep, I confirm that it is now working perfectly:

![image](https://user-images.githubusercontent.com/41893936/83629772-0162fd80-a59b-11ea-94d0-854818c63aad.png)
