### ISSUE TITLE
New device parsing json

### ISSUE THREAD

**Issue by JiriKursky** [jm-73/Indego#56]
Hello, there are issues when it is a new device. In these lines should be testing on NoneType or better try - exception.

File "/usr/local/lib/python3.7/site-packages/pyIndego/__init__.py", line 495, in getLastCutting
    tmp_datetime = tmp_json['last_mowed']
TypeError: 'NoneType' object is not subscriptable

File "/usr/local/lib/python3.7/site-packages/pyIndego/__init__.py", line 511, in getNextCutting
    tmp_datetime = tmp_json['mow_next']
TypeError: 'NoneType' object is not subscriptable

Kind Regars, Jiri

**Comment by Shamshala** [comment]
The second error appears even with "old" device. :slightly_smiling_face: SmartMowing must be turned on to meet the condition.

**Comment by Shamshala** [comment]
The second error appears even for an "old" device. :slightly_smiling_face: SmartMowing must be turned on to meet the condition.

**Comment by JiriKursky** [comment]
I have bought mower yesterday, it is "on" and Bosch app is running well. The next date (mow_next) is not set up in calendar. My calendar is null and I think that it is root case.

**Comment by Shamshala** [comment]
Just saying. :)

**Comment by JiriKursky** [comment]
Thank you, I am going to close that.
