### ISSUE TITLE
Configuration Example for S/N starting with 0

### ISSUE THREAD

**Issue by bekkm** [jm-73/Indego#58]
Dear JM,

one comment which took me quite some time to figure out and might be helpful to add/change in your documentation.

If you have a serial number starting with a 0 you need to put it in the secrets.yaml in "" e.g. "0123456789" otherwise it will not work.

If you just enter it, it does not work as it is interpreted wrongly, . Omitting the leading zero will result in a failed login because of invalid api path.

If you have some time left...

KR,
Markus

**Comment by jm-73** [comment]
I have updated the docs for version 0.9 to set username, password and serial inside "". Hope that will help future users.
