### ISSUE TITLE
Battery Sensor not showing

### ISSUE THREAD

**Issue by flrnhlbg** [jm-73/Indego#61]
Battery % and Battery V not available since update.

Indego is online.

Version: 0.9
Indigo S+350

**Comment by pfriedrich84** [comment]
Indego 350 Connect is showing. Anything in the logs?

**Comment by flrnhlbg** [comment]
Wait a Moment. That was a problem with my mower. Took it out of the station, shut it off and put it back in. Worked after turning it in again.
