### ISSUE TITLE
Change service name (breaking change)

### ISSUE THREAD

**Issue by jm-73** [jm-73/Indego#64]
Change name to service indego.mower_command.
Remove Mower and rename it to indego.command.

**Comment by Shamshala** [comment]
Also, what about merging `indego.smart_mow` into `indego.command` as well? 

For example:
```
service: indego.command
data:
  smartmowing: true/false
```
Or do we need two services for a reason which i'm missing?

**Comment by jm-73** [comment]
The plan is to make it possible for everyone to skip the Bosch App and the Bosch SmartMowing. And to be able to make HomeAssistant to have total control!

I have also been thinking about if I should have all commands in the indego.command service.

**Comment by Shamshala** [comment]
:eyes: :rocket: :tada: :tada: :tada:

**Comment by jm-73** [comment]
But I need your help with what kind of logic we should implement to help users with their Hassio setu of the mower. I will implement that the indego.command will accept both mow commands (mow, pause, returnToDock) AND smartmowing (enable/disable).

**Comment by Shamshala** [comment]
I'm not sure about what logic do you mean. IMHO the logic behind the commands and enabling/disabling smartmowing is pretty straightforward. :+1: 

If we are already talking about implementing calendar settings :eyes: , then i was wondering the same thing but then i realized we have a nice new Calendar integration for HA (never used it though :laughing: , perhaps now it'll get the right purpose), which could be pretty user friendly.

**Comment by jm-73** [comment]
Implemented in 1.3
