### ISSUE TITLE
Best way to implement UI for mow / dock / pause?

### ISSUE THREAD

**Issue by Swiftnesses** [jm-73/Indego#69]
Hi,

Thank you for this excellent component :-)

I'm wondering the best way to implement a UI to trigger  / show certain states.

In the past I've used the vacuum class for my mowers so I could take advantage of the native UI, is this something you've considered?

**Comment by dykandDK** [comment]
You can use standard Lovelace components to get a similar lock and feel as form the vaccum cards:

![image](https://user-images.githubusercontent.com/59793798/84518632-48ef3500-acd1-11ea-95e9-dc342c1311fa.png)

See below for my yaml code:

      #---------------------------------------------------------------
      # Bosch Indego lawnmover
      #---------------------------------------------------------------
      - image: /local/assets/indego.jpg
        state_filter:
          - null
        type: picture-elements
        elements:
          - type: state-label
            entity: sensor.indego_mower_alert
            suffix: ' Alerts'
            style:
              top: 12%
              left: 10px
              font-size: 15px
              max-width: 1px
          - type: state-label
            entity: sensor.indego_lawn_mowed
            suffix: ' Complete'
            style:
              top: 26%
              left: 10px
              font-size: 15px
              max-width: 1px
          - type: state-label
            entity: sensor.indego_battery
            prefix: 'Battery : '
            style:
              top: 40%
              left: 10px
              font-size: 15px
              max-width: 1px
          - type: state-label
            entity: sensor.indego_mower_state_detail
            style:
              top: 54%
              left: 10px
              font-size: 15px
              max-width: 1px
          - type: state-label
            entity: sensor.indego_mowing_mode
            prefix: 'Mode : '
            style:
              top: 68%
              left: 272px
              font-size: 15px
              max-width: 1px
          - type: state-label
            entity: sensor.indego_runtime_total
            prefix: 'Runtime : '
            style:
              top: 82%
              left: 272px
              font-size: 15px
              max-width: 1px
          - type: icon
            title: Mow
            icon: 'mdi:play'
            entity: input_boolean.indego_mow
            tap_action:
              action: call-service
              service: indego.mower_command
              service_data:
                command: mow
            style:
              top: 15%
              left: 70%
              '--iron-icon-fill-color': '#FFFFFF'
              '--iron-icon-height': 40px
              '--iron-icon-width': 40px
          - type: icon
            title: Pause
            icon: 'mdi:pause'
            entity: input_boolean.indego_pause
            tap_action:
              action: call-service
              service: indego.mower_command
              service_data:
                command: pause
            style:
              top: 15%
              left: 83%
              '--iron-icon-fill-color': '#FFFFFF'
              '--iron-icon-height': 40px
              '--iron-icon-width': 40px
          - type: icon
            title: Home
            icon: 'mdi:home'
            entity: input_boolean.indego_home
            tap_action:
              action: call-service
              service: indego.mower_command
              service_data:
                command: returnToDock
            style:
              top: 15%
              left: 95%
              '--iron-icon-fill-color': '#FFFFFF'
              '--iron-icon-height': 40px
              '--iron-icon-width': 40px
          - type: state-label
            entity: sensor.indego_mower_state
            prefix: 'Status : '
            style:
              top: 54%
              left: 272px
              font-size: 15px
              max-width: 1px
          #- type: !env_var 
          - type: state-label
            entity: sensor.indego_last_completed
            prefix: 'Last cut : '
            style:
              top: 68%
              left: 10px
              font-size: 15px
              max-width: 1px
          - type: state-label
            entity: sensor.indego_next_mow
            prefix: 'Next cut : '
            style:
              top: 82%
              left: 10px
              font-size: 15px
              max-width: 1px

**Comment by jm-73** [comment]
I am using an earlier version of your card. It is really great! I want to publish it to HACS!

**Comment by urbatecte** [comment]
Definitively a great card 🥇

**Comment by Shamshala** [comment]
I'm using slightly modest card 🙂
![57AD2D03-FBD8-45F9-A6A8-865DE954AA0D](https://user-images.githubusercontent.com/28995424/84551558-47902d80-ad0e-11ea-81b5-e75d95f40bbd.jpeg)

**Comment by jm-73** [comment]
You guys should make a HACS Front End card from this codes. They are awsome.

**Comment by jm-73** [comment]
I am going to close this issue as it is not related to the integration. It as up to you guys to contribute with an lovelace frontend component in HACS.
