### ISSUE TITLE
First setup: AttributeError: 'IndegoAPI' object has no attribute '_model_voltage'

### ISSUE THREAD

**Issue by Olum-hack** [jm-73/Indego#70]
Hello,
I get that message in the log during first setup:
Error during setup of component indego
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 175, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/indego/__init__.py", line 54, in setup
    Mower()
  File "/config/custom_components/indego/__init__.py", line 113, in __init__
    IndegoAPI_Instance.ModelVoltage()
  File "/usr/local/lib/python3.7/site-packages/pyIndego/__init__.py", line 773, in ModelVoltage
    return self._model_voltage
AttributeError: 'IndegoAPI' object has no attribute '_model_voltage'

**Comment by jm-73** [comment]
If you update to release 1.2 of the integration you should be able to start the integration. If you look in the log, there should be warning messages (search for "Mower Model Description not in database"). Then post the modelnumber for your mower here so I can add it to the model database.

**Comment by Olum-hack** [comment]
I get many different messages:

Error during setup of component indego
13:42:21 – custom_components/indego/__init__.py (ERROR)

BatteryPerCentAdjusted ERROR!
13:42:18 – custom_components/indego/__init__.py (ERROR)

Setup of indego is taking over 10 seconds.
13:42:14 – __main__.py (WARNING)

ModelVoltageMax bareToolnumber ERROR!!! = 3600HB0106
13:42:05 – custom_components/indego/__init__.py (ERROR)

ModelVoltageMin bareToolnumber ERROR!!! = 3600HB0106
13:42:05 – custom_components/indego/__init__.py (ERROR)

Mower Model Voltage not in database! ModelMumber 3600HB0106
13:42:05 – custom_components/indego/__init__.py (WARNING)

Mower Model Description not in database! ModelMumber 3600HB0106
13:42:05 – custom_components/indego/__init__.py (WARNING)

**Comment by Olum-hack** [comment]
My Model ist 
3600hb0106 -> Indego S+ 400

**Comment by jm-73** [comment]
Thanks! Will be added in next release!

**Comment by jm-73** [comment]
Implemented in 1.3

**Comment by Olum-hack** [comment]
Thank you.
It is working.
