### ISSUE TITLE
Mower state code : 101, 1005 and 1038

### ISSUE THREAD

**Issue by urbatecte** [jm-73/Indego#82]
Hi Jens,

Please find here after additionnal code (translated from french to english, feel free to correct it ;o)
1005 : Docking-station connection impossible
1038 : Mower immobilized
101  : Picking-up detected

No urgent to include it in a dedicated release.
Thanks for your awesome job !

**Comment by jm-73** [comment]
Thanks! Will be included in the next release. Good work!!!

**Comment by urbatecte** [comment]
Seems that I get 2 codes for mower immobilized.
1038 and 1138 ...
I will annoy a bit the mower to try to confirm ;o)

**Comment by jm-73** [comment]
Will be fixed in 1.6!
