### ISSUE TITLE
No updates recieved after aprox 3,5h

### ISSUE THREAD

**Issue by jm-73** [jm-73/Indego#87]
Session times out after 3,5h and no updates are being recieved

**Comment by eavanvalkenburg** [comment]
Do you mean that the `context-id` gets outdated after 3,5 h?

**Comment by jm-73** [comment]
In the 2.0. Not tested the 3.0 yet. I think the 2.0 suffers from incompability between the pyIndego vs Indego integration incompability.

**Comment by eavanvalkenburg** [comment]
it would make sense because it the context-id is basically a token that you get after logging in and that should have an experiation time, probably easiest to schedule a task for login every 3 hours then.

**Comment by jm-73** [comment]
Could we implement that a 401 error triggers a login?

**Comment by eavanvalkenburg** [comment]
yeah that is even better!

**Comment by jm-73** [comment]
Bug confirmed in version 3.0 also

**Comment by eavanvalkenburg** [comment]
I think this was fixed with 2.0.12, could you confirm?

**Comment by jm-73** [comment]
Fixed in 3.1
