### ISSUE TITLE
Services does not exist after upgrade to 0.6

### ISSUE THREAD

**Issue by nsimb** [jm-73/Indego#9]
Got error when running my old script to start the Indego.
Checked it out in service tab and there is no longer any service "indego.mower_command"

No error in log when setting up the custom component

worked in 0.4 (or was previous 0.3)
Let me know if you need further information

//nicklas

**Comment by jm-73** [comment]
Try the branch 6.1 (misnamed, should be 0.6.1 :-) )

Let me know if this works for you!

**Comment by nsimb** [comment]
sorry for the late test, just tried it and its working again.
Thanks for the fix!

**Comment by jm-73** [comment]
NP, glad it is working again!
