### ISSUE TITLE
Attributes in Alert sensors since v3.1

### ISSUE THREAD

**Issue by Shamshala** [jm-73/Indego#93]
I'm not sure what was discused but these don't seem right to me. :slightly_smiling_face: 

`sensor.indego_************_mower_alert`
shows empty attributes: `total operation time`, `total mowing time`, `total charging time`

&

`binary_sensor.indego_************_alert`
shows attributes `alerts count` and `alert details` which contains not just alert message by itself but also some additional format coding and probably non required informations like: `date=`, `push=True`, `read_status='unread'`, `headline=`, `alert_description=`, `message=`, `flag='warning'`, `alert_description=`

**Comment by Olum-hack** [comment]
I have the same situation since 3.1. 
All Entities contain the ID of the indego.

**Comment by jm-73** [comment]
The binary alert sensor (sensor.indego_xxxxxxxxx_alert) is probably going to replace the alert sensor. And yes, the sensor names are changes (I added that to the release notes after your correct observation).

**Comment by Shamshala** [comment]
Yeah, i was confused after i updated to new version and all my sensors were gone, so i reverted back but then i realized you could just slightly change the sensor names, updated the integration again and checked 😆 

Ok then, so only the format coding is "wrong". 🙂

**Comment by Shamshala** [comment]
@jm-73 Yeah, i was confused after i updated to new version and all my sensors were gone, so i reverted back but then i realized you could just slightly change the sensor names, updated the integration again and checked 😆 

Ok then, so only the format coding is "wrong". 🙂

**Comment by jm-73** [comment]
Names are still changed, and will be in forward releases.the alert sensor is replaced with the binary alert sensor form release 3.3

**Comment by Shamshala** [comment]
And what about the formating? The errors are not readable for a bare user because of that.

**Comment by Shamshala** [comment]
And what about the formating? The errors/alerts are not readable for a bare user because of that. Names weren't the main issue.

As i've mentioned above, it includes descriptors juch as date=, push=True, read_status='unread', headline=, alert_description=, message=, flag='warning', alert_description=

**Comment by Shamshala** [comment]
And what about the formating? Errors/alerts are not readable for a bare user because of that. Sensor names weren't the main issue.

As i've mentioned above, it includes descriptors such as `date=`, `push=True`, `read_status='unread'`, `headline=`, `alert_description=`, `message=`, `flag='warning'`, `alert_description=`, etc.

**Comment by Shamshala** [comment]
I see, it's fixed in v3.3 🎉 

Too bad it's in english again. Previous versions were in english, v3.1 shows alerts in user's native language 🥰 (despite the descriptors).

**Comment by jm-73** [comment]
Do you want a sensor with the whole localized alert message? I dont know how to make it a good looking sensor. We have two alternatives:
1. translate the english "short alert messages" to other langages.
2. Make a Alert detailed sensor with the whole localized alert message (they are quite long some of them)

What is your take om this? How du you use it?

@eavanvalkenburg and me talked about integrating the Indego alerts in HA warnings and alerts. We have also been working on methods to flag alert messages as read and also to remove them. So hopefully we get some cool functions later on.

**Comment by Shamshala** [comment]
I don't think we need a specific sensor for this. In the earlier versions i was about to ask if it's possible to implement translation files because of the messages, but in v3.1 i noticed the alerts are passed in "native" language as well so i thought "well, it's not necessary".

Just passing "short alert messages" in the `binary_sensor.indego_************_alert` attribute as it is now but in user's language could be nice. But when i think about it, translation files could be more friendly approach and it can can handle also States and State details. I don't know how many foreigners (i mean non-english speaking natively) will use it but translation is a nice touch. :slightly_smiling_face:

**Comment by jm-73** [comment]
Problem is, the long alert descriptions are native. They are collected from the Bosch API. Bosch has made localized alert messages. The short ones are added by me to fit into the alert sensor and give a clue about the nature if the alert.

So if we are going with the short ones, we are stuck with the english ones. The longer alert messages are natively available localized.

Long term plan is to incorporate the alerts into native HA log/alerts.

**Comment by eavanvalkenburg** [comment]
The big question for me is what do you want to do with those alert sensors @Shamshala? For me the fact that there is a alert already means I have to do something (or not) but I don't particularly care what kind or other details, there are two complexities in making it look good, 1) there can be multiple alerts, so just a simple list of the fields mentioned doesn't work, so something like this:
``` json
alert_id: 5f05096b63c53486cd759bd1
error_code: ntfy_blade_life
headline: Maintenance Advice
etc.
```
won't work, or we would have to create a seperate sensor for each alert and that definitely doesn't help anything in my opinion. 2) there is a status with the alerts (read, unread) which we should do something with.

My current thinking is that we should integrate create a HA notification for a unread alert, and once dismissed that sets it to read, and they you either delete it through the app or we create a service in HA that you can call to do that with. But we could also set any alert as a HA notification, and delete upon dismissal, I tend to not read HA notifications after startup very carefull so wouldn't want to do the second route, but would like to hear what the rest think. I also just realized that maybe the binary_sensor alert should only be ON when there are unread alerts, not when there are old alerts? What do you think @jm-73, @Shamshala, @iMarkus, @bekkm ?

**Comment by UltraSub** [comment]
The only thing I would really like to see is to be able to use alerts for sending me a notification containing what is wrong, so a long description would be handy. I personally don't care about localization. The API returns english, so that's it. Creating translations in code is something I see as a stretch.

Service call to clear alerts would be cool, automation would send me a message containing long description and then clear the alert so I don't need to start the app to clear manually.

**Comment by jm-73** [comment]
There should be an binary sensor telling if there are a new alert. Thats the most useful case. If the alert sensor then could include the error message in some way, then users could get HA to send alerts to devices/phones when it occurs.
But I am not sure how to implement this in a nice way in HA?

**Comment by jm-73** [comment]
Maybe an sensor with the count of the (new) alerts? And a function to reset the counter/acknowledge the alerts?

**Comment by Shamshala** [comment]
@eavanvalkenburg The Alerts itself should be just informative as you mentioned in your text. Sure, sensor On/Off in case of new alerts is probably enough to incorporate into some automations but i though this integration is about to "replace" the app so to know what's wrong is imho must-have (i think we don't need the "recommendation" part of the alerts, but @UltraSub is right it could be handy).

HA notification for unread alerts is exactly what i would expect, as well as the service for clearing the notifications can be handy. :+1: 

@UltraSub I don't know, english isn't the best option for everyone in my opinion. Well even HA has multiple languages, so to have the whole HA's interface "native" and few integrations containing english is kinda odd looking - sure nothing serious though. Translation could be handled the same way as other integrations use, seperate file which includes list of "this"="means that"
Sure, one can do some custom template sensors to rewrite every message or status though.

**Comment by UltraSub** [comment]
Agree about multilingual is good to have. Just think there are more important things the guys who are coding spend there precious time om. That's why I said stretch. Could be good to setup a system with files so other users would be able to help translating by pushing the translations?

**Comment by Shamshala** [comment]
No complains here (i know excatly what you mean by precious time) i just wanted to mention that because i noticed there was a "translation" in one version and in newer version is gone again. :slightly_smiling_face: Original post was about attributes :smile: 

I didn't plan to broad it in as a top list feature.

**Comment by jm-73** [comment]
I think this conversation is over for this time. We will continue to discuss this in the Discord channel if there are any remaining questions.
