### ISSUE TITLE
Update "available"

### ISSUE THREAD

**Issue by Shamshala** [jm-73/Indego#95]
Just to make sure `binary_sensor.indego_*******_update_available` is/was supposed to be for as a new firmware indication, am i right? If so, after some time since update to v3.1 at one point the sensor got triggered and shows "True" for every hour with less than a second "False" interrupts.
There wasn't any firmware update for my mower. 🙂

EDIT: Ok after HA restart the sensor stays "False" for exact an hour, then starts to be always "True" with <1s "False" interrupts every hour (and it also wakes the mower for few minutes).

**Comment by jm-73** [comment]
I have also noticed this. I will investigate this.

**Comment by jm-73** [comment]
I cannot see this any more. Could it have been fixed with the rewrite of all code?

**Comment by Shamshala** [comment]
Yep, me neither. I doubt i ever gonna get any new firmware for my old mower so from my perspective it's fixed now.😆
