### ISSUE TITLE
iPhone app showing incorrect date/time for sensors

### ISSUE THREAD

**Issue by jm-73** [jm-73/Indego#98]
Sensor "Last Mow" and "Next Mow" shows "Invalid Date" as sensor value. The date time value seems to be correct when showing details for the sensors.

Appeared in version 3.2

**Comment by Shamshala** [comment]
Still present in version v3.3

And in desktop it produces number which is out of more-info window border:
![indego](https://user-images.githubusercontent.com/28995424/87234418-e624b280-c3d0-11ea-9cb6-efe6d7071879.png)

**Comment by jm-73** [comment]
Yes, I have noticed that. It is also problem with the time representation as it is in UTC and not local time.

**Comment by jm-73** [comment]
The offset is now correct in 3.4. But the formatting is wrong when opening the sensor (as the screendump abonve) and the HA App (IOS) does not show the date.

Could you have a look at this, @eavanvalkenburg ?

**Comment by eavanvalkenburg** [comment]
Yeah, I'm super confused by this and think it is more a HA/Front end bug than our component, because I've seen them displayed correctly and invalid without any code changes...

**Comment by Shamshala** [comment]
Ok, if you remove the **unit of meassurment** it at least align the time in the box. (so it won't overlap it outside)

**Comment by Shamshala** [comment]
Ok, if you remove the **unit of measurement** it at least aligns the time in the box. (so it won't overlap the window)

**Comment by jm-73** [comment]
I will have a look into pyIndego helper function that does the formatting of the time. And then test in Integration also. Maybe I release a beta to get more people to test the code.

**Comment by eavanvalkenburg** [comment]
I saw this, and changed the lines that update the state for both sensors by adding `.isoformat()` to them in the custom component code in my prod. For instance: 
```python
self.entities[ENTITY_LAST_COMPLETED].state = self.indego.last_completed_mow.isoformat()
```
that is enough, no need to change the package, that gives a datetime object, which is the most universal. Haven't had time to properly put that on GH, so feel free to do that!

**Comment by jm-73** [comment]
Ok, I will pull this into GH and test it!

**Comment by jm-73** [comment]
With
```.isoformat()```
the sensor has the value
```2020-07-11T15:20:54.663000+02:00 ISO8601```

Without, it has the value
```2020-07-11 15:20:54.663000+02:00 ISO8601```

So no real difference here, @eavanvalkenburg...

**Comment by eavanvalkenburg** [comment]
> Yep, by additing **T** instead of space makes it work on iOS as well. :slightly_smiling_face: 

@jm-73 This is exactly the difference we wanted!

**Comment by jm-73** [comment]
Ok, but the sensor value still flows the GUI...

**Comment by eavanvalkenburg** [comment]
And without the unit of measurement?

**Comment by Shamshala** [comment]
@jm-73 **Unit of measurement** needs to be removed as well as i mentioned above. 🙂

**Comment by jm-73** [comment]
I got the same result when removing the unit of measurement...

**Comment by eavanvalkenburg** [comment]
What result are tot expecting? For me the expectation is that they show relative time in most visuals and full details when clicking on it...

**Comment by jm-73** [comment]
I am expecting a readable format for the sensor. Eg:
2020-07-16 15:55
5 june 2020 02:15 AM
Not a value that doesnt fit in the GUI.

**Comment by jm-73** [comment]
The sensor works, it does what it should, its just the representation in the details pane...

**Comment by jm-73** [comment]
How has other integrations that incorporates time solved this? Is it a HA bug? Can we format the details pane?

**Comment by eavanvalkenburg** [comment]
Then we shouldn't do anything else with it, the only thing we could do is round off the last completed mow to get rid of the milliseconds, but we need it in this format (datetime with a T and timezone) otherwise people making automations with it will have to do all sorts of annoying stuff to be able to use it as a datetime, while formatting is a front-end thing, so for instance I have it in a homefeed card like this, which is exactly what I like! 
![image](https://user-images.githubusercontent.com/13749212/87636037-59ffeb80-c740-11ea-80a2-763887d3ecf2.png)

Otherwise people can create customized sensors like this: https://community.home-assistant.io/t/date-formatting/17461

**Comment by Shamshala** [comment]
If i understand you correctly, there isn't a way over it i'm afraid. The HA frontend needs this format for correct representation. Unfortunatelly i don't have similar time sensor to look whether it's managable differently but when you look at automations, it uses this format as well.

**Comment by jm-73** [comment]
OK, I hear you! And I understand that it is technically correct. 
In my mind the gui should cut/adjust the correct value and the technical representation of the value and show a human readable representation instead. At least a value that fits in the GUI.
But that seems that I have to ask the HA team to consider.

I think we could close this issue now, as I have committed the changes to the develop branch.

Any other thoughts?
